use crate::types::AbiType::{F64, I8, I32, I64, Ptr, Void};
use crate::types::Tier::{Both, Cranelift, Llvm};
use crate::types::{AbiSig, RuntimeEntry};

/// Build a [`RuntimeEntry`] from name, typed params, return type, tier, and docs.
macro_rules! rt {
    ($name:literal, ($($p:expr),*) -> $ret:expr, $tier:expr, $docs:literal) => {
        RuntimeEntry {
            name: $name,
            sig: AbiSig {
                params: &[$($p),*],
                ret: $ret,
            },
            tier: $tier,
            docs: $docs,
        }
    };
}

/// Complete registry of every `gos_rt_*` C-ABI runtime symbol.
///
/// Entries are sorted alphabetically by name so `lookup` can be
/// replaced with binary search if the table grows beyond ~500 entries.
/// A test asserts the sort invariant.
pub const REGISTRY: &[RuntimeEntry] = &[
    rt!("gos_rt_arena_restore", (I64) -> Void, Cranelift, "Restore the bump-arena high-water mark to a saved position."),
    rt!("gos_rt_arena_save", () -> I64, Cranelift, "Save and return the current bump-arena high-water mark."),
    rt!("gos_rt_arr_format_bool", (Ptr, I64) -> Ptr, Cranelift, "Format a fixed-size bool array as a debug string."),
    rt!("gos_rt_arr_format_f64", (Ptr, I64) -> Ptr, Cranelift, "Format a fixed-size f64 array as a debug string."),
    rt!("gos_rt_arr_format_i64", (Ptr, I64) -> Ptr, Cranelift, "Format a fixed-size i64 array as a debug string."),
    rt!("gos_rt_arr_format_string", (Ptr, I64) -> Ptr, Cranelift, "Format a fixed-size String array as a debug string."),
    rt!("gos_rt_arr_iter", (Ptr) -> Ptr, Cranelift, "Create an iterator over a fixed-size array."),
    rt!("gos_rt_arr_iter_free", (Ptr) -> Void, Cranelift, "Free a fixed-size array iterator created by gos_rt_arr_iter."),
    rt!("gos_rt_arr_iter_next", (Ptr) -> Ptr, Cranelift, "Advance a fixed-size array iterator; returns null when exhausted."),
    rt!("gos_rt_arr_len", (Ptr) -> I64, Cranelift, "Return the element count of a fixed-size GosArr."),
    rt!("gos_rt_arr_sort_by_aggr", (Ptr, I64, I64, Ptr) -> Void, Cranelift, "Sort a fixed-size array of multi-slot aggregate elements; the comparator receives element pointers."),
    rt!("gos_rt_arr_sort_by_i64", (Ptr, I64, Ptr) -> Void, Cranelift, "Sort a fixed-size array using an i64-keyed comparator."),
    rt!("gos_rt_atomic_i64_cas", (Ptr, I64, I64) -> I32, Cranelift, "Compare-and-swap an AtomicI64 with sequentially-consistent ordering."),
    rt!("gos_rt_atomic_i64_cas_acq_rel", (Ptr, I64, I64) -> I32, Cranelift, "Compare-and-swap an AtomicI64 with acquire-release ordering."),
    rt!("gos_rt_atomic_i64_fetch_add", (Ptr, I64) -> I64, Cranelift, "Atomically add to an i64 and return the previous value."),
    rt!("gos_rt_atomic_i64_fetch_add_acqrel", (Ptr, I64) -> I64, Cranelift, "Atomically add to an i64 with acquire-release ordering."),
    rt!("gos_rt_atomic_i64_load", (Ptr) -> I64, Cranelift, "Load an AtomicI64 value with sequentially-consistent ordering."),
    rt!("gos_rt_atomic_i64_load_acquire", (Ptr) -> I64, Cranelift, "Load an AtomicI64 value with acquire ordering."),
    rt!("gos_rt_atomic_i64_load_relaxed", (Ptr) -> I64, Cranelift, "Load an AtomicI64 value with relaxed ordering."),
    rt!("gos_rt_atomic_i64_new", (I64) -> Ptr, Both, "Allocate and initialise a new AtomicI64."),
    rt!("gos_rt_atomic_i64_store", (Ptr, I64) -> Void, Cranelift, "Store a value into an AtomicI64 with sequentially-consistent ordering."),
    rt!("gos_rt_atomic_i64_store_relaxed", (Ptr, I64) -> Void, Cranelift, "Store a value into an AtomicI64 with relaxed ordering."),
    rt!("gos_rt_atomic_i64_store_release", (Ptr, I64) -> Void, Cranelift, "Store a value into an AtomicI64 with release ordering."),
    rt!("gos_rt_atomic_i64_swap", (Ptr, I64) -> I64, Cranelift, "Atomically swap an AtomicI64 and return the old value."),
    rt!("gos_rt_bool_to_str", (I32) -> Ptr, Both, "Format a bool as \"true\" or \"false\"."),
    rt!("gos_rt_btmap_free", (Ptr) -> Void, Cranelift, "Drop a BTreeMap and release its memory."),
    rt!("gos_rt_btmap_get_or", (Ptr, Ptr, I64) -> I64, Cranelift, "Look up a string key in a BTreeMap<String,i64>; return default if absent."),
    rt!("gos_rt_btmap_insert", (Ptr, Ptr, I64) -> Void, Cranelift, "Insert or update a string-to-i64 entry in a BTreeMap."),
    rt!("gos_rt_btmap_keys", (Ptr) -> Ptr, Cranelift, "Return all keys of a BTreeMap<String,i64> as a GosVec."),
    rt!("gos_rt_btmap_len", (Ptr) -> I64, Cranelift, "Return the number of entries in a BTreeMap."),
    rt!("gos_rt_btmap_new", () -> Ptr, Cranelift, "Allocate an empty BTreeMap<String,i64>."),
    rt!("gos_rt_bufio_scanner_new", (Ptr) -> Ptr, Cranelift, "Wrap a stream in a buffered line scanner."),
    rt!("gos_rt_bufio_scanner_scan", (Ptr) -> I8, Cranelift, "Advance the scanner to the next line; returns 1 if a line was read."),
    rt!("gos_rt_bufio_scanner_text", (Ptr) -> Ptr, Cranelift, "Return the current line text from a bufio scanner."),
    rt!("gos_rt_chan_close", (Ptr) -> Void, Cranelift, "Mark a channel as closed; future sends will panic."),
    rt!("gos_rt_chan_drop", (Ptr) -> Void, Cranelift, "Drop a channel reference and release its memory."),
    rt!("gos_rt_chan_new", (I32, I64) -> Ptr, Cranelift, "Allocate a new typed channel with an optional buffer capacity."),
    rt!("gos_rt_chan_recv", (Ptr, Ptr) -> I32, Cranelift, "Receive one value from a channel; blocks until one is available."),
    rt!("gos_rt_chan_recv_option", (Ptr) -> Ptr, Cranelift, "Receive one value wrapped in Option; returns None if channel is closed."),
    rt!("gos_rt_chan_send", (Ptr, Ptr) -> Void, Cranelift, "Send one value into a channel, blocking if the buffer is full."),
    rt!("gos_rt_chan_try_recv", (Ptr, Ptr) -> I32, Cranelift, "Non-blocking channel receive; returns 0 if no value is ready."),
    rt!("gos_rt_chan_try_recv_option", (Ptr) -> Ptr, Cranelift, "Non-blocking receive returning an Option pointer."),
    rt!("gos_rt_chan_try_send", (Ptr, Ptr) -> I32, Cranelift, "Non-blocking channel send; returns 0 if the channel is full."),
    rt!("gos_rt_char_to_str", (I32) -> Ptr, Both, "Convert a Unicode scalar (i32) to its UTF-8 String representation."),
    rt!("gos_rt_chunked_decode", (Ptr) -> Ptr, Cranelift, "Concatenate the data chunks from an HTTP/1.1 chunked-encoded body."),
    rt!("gos_rt_chunked_encode", (Ptr) -> Ptr, Cranelift, "Wrap one buffer in HTTP/1.1 chunked transfer-encoding."),
    rt!("gos_rt_concat_bool", (I32) -> Void, Both, "Append a bool to the active concat buffer."),
    rt!("gos_rt_concat_char", (I32) -> Void, Both, "Append a char to the active concat buffer."),
    rt!("gos_rt_concat_f64", (F64) -> Void, Both, "Append an f64 to the active concat buffer."),
    rt!("gos_rt_concat_f64_prec", (F64, I64) -> Void, Cranelift, "Append an f64 with fixed decimal precision to the active concat buffer."),
    rt!("gos_rt_concat_finish", () -> Ptr, Both, "Finalise the active concat buffer and return the result String."),
    rt!("gos_rt_concat_i64", (I64) -> Void, Both, "Append an i64 to the active concat buffer."),
    rt!("gos_rt_concat_init", () -> Void, Both, "Initialise a new concat buffer for format! or string concatenation."),
    rt!("gos_rt_concat_str", (Ptr) -> Void, Both, "Append a String slice to the active concat buffer."),
    rt!("gos_rt_concat_u64", (I64) -> Void, Both, "Append a u64 to the active concat buffer."),
    rt!("gos_rt_duration_from_millis", (I64) -> I64, Cranelift, "Construct a Duration from a millisecond count."),
    rt!("gos_rt_duration_from_secs", (I64) -> I64, Cranelift, "Construct a Duration from a second count."),
    rt!("gos_rt_eprint_str", (Ptr) -> Void, Both, "Write a string to stderr without a trailing newline."),
    rt!("gos_rt_eprintln", () -> Void, Both, "Write a newline to stderr."),
    rt!("gos_rt_error_cause", (Ptr) -> Ptr, Cranelift, "Return the wrapped cause error, or null if none."),
    rt!("gos_rt_error_is", (Ptr, Ptr) -> I8, Cranelift, "Walk the cause chain and return 1 if any error matches the needle."),
    rt!("gos_rt_error_message", (Ptr) -> Ptr, Cranelift, "Return the top-level message string of an errors::Error."),
    rt!("gos_rt_error_new", (Ptr) -> Ptr, Cranelift, "Construct a new errors::Error from a message string."),
    rt!("gos_rt_error_wrap", (Ptr, Ptr) -> Ptr, Cranelift, "Wrap a cause error with an additional message."),
    rt!("gos_rt_errors_join", (Ptr, I64) -> Ptr, Cranelift, "Combine N errors from a raw pointer array into one."),
    rt!("gos_rt_errors_join_vec", (Ptr) -> Ptr, Cranelift, "Combine a GosVec of errors into one joined error."),
    rt!("gos_rt_exec_kill", (I64) -> I64, Cranelift, "Send SIGKILL to a spawned child process by its handle ID."),
    rt!("gos_rt_exec_run", (Ptr, Ptr) -> Ptr, Cranelift, "Run a process synchronously and return its combined output."),
    rt!("gos_rt_exec_spawn", (Ptr, Ptr) -> Ptr, Cranelift, "Spawn a child process and return a handle for later use."),
    rt!("gos_rt_exit", (I32) -> Void, Both, "Exit the process immediately with the given status code."),
    rt!("gos_rt_f64_prec_to_str", (F64, I64) -> Ptr, Both, "Format an f64 with a fixed number of decimal places."),
    rt!("gos_rt_f64_to_str", (F64) -> Ptr, Both, "Convert an f64 to its shortest round-trip decimal string."),
    rt!("gos_rt_file_server_new", (Ptr, Ptr) -> Ptr, Cranelift, "Allocate a FileServer rooted at a directory with an optional path prefix."),
    rt!("gos_rt_file_server_serve", (Ptr, Ptr) -> Ptr, Cranelift, "Serve a request against a FileServer; returns Result<Response, Error>."),
    rt!("gos_rt_flag_cell_load_bool", (Ptr) -> I64, Cranelift, "Load the bool value from a flag cell."),
    rt!("gos_rt_flag_cell_load_f64", (Ptr) -> F64, Cranelift, "Load the f64 value from a flag cell."),
    rt!("gos_rt_flag_cell_load_i64", (Ptr) -> I64, Cranelift, "Load the i64 value from a flag cell."),
    rt!("gos_rt_flag_cell_load_str", (Ptr) -> Ptr, Cranelift, "Load the String value from a flag cell."),
    rt!("gos_rt_flag_cell_load_vec", (Ptr) -> Ptr, Cranelift, "Load the Vec value from a flag cell."),
    rt!("gos_rt_flag_map_get", (Ptr, Ptr) -> Ptr, Cranelift, "Look up a named flag in a parsed flag map."),
    rt!("gos_rt_flag_parse", (Ptr) -> Ptr, Cranelift, "Parse a flat Vec<String> of CLI args using the top-level flag set."),
    rt!("gos_rt_flag_set_bool", (Ptr, Ptr, I8, Ptr) -> Ptr, Cranelift, "Register a boolean flag on a flag set."),
    rt!("gos_rt_flag_set_duration", (Ptr, Ptr, I64, Ptr) -> Ptr, Cranelift, "Register a duration flag on a flag set."),
    rt!("gos_rt_flag_set_float", (Ptr, Ptr, F64, Ptr) -> Ptr, Cranelift, "Register a float flag on a flag set."),
    rt!("gos_rt_flag_set_int", (Ptr, Ptr, I64, Ptr) -> Ptr, Cranelift, "Register an integer flag on a flag set."),
    rt!("gos_rt_flag_set_new", (Ptr) -> Ptr, Cranelift, "Allocate a new named flag set."),
    rt!("gos_rt_flag_set_parse", (Ptr, Ptr) -> Ptr, Cranelift, "Parse args into a named flag set; returns a Result error on failure."),
    rt!("gos_rt_flag_set_short", (Ptr, I64) -> Void, Cranelift, "Set the maximum positional-argument count for a flag set."),
    rt!("gos_rt_flag_set_string", (Ptr, Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Register a string flag on a flag set."),
    rt!("gos_rt_flag_set_string_list", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Register a repeated-string flag on a flag set."),
    rt!("gos_rt_flag_set_uint", (Ptr, Ptr, I64, Ptr) -> Ptr, Cranelift, "Register an unsigned-integer flag on a flag set."),
    rt!("gos_rt_flag_set_usage", (Ptr) -> Ptr, Cranelift, "Return the usage/help string for a flag set."),
    rt!("gos_rt_flush_stdout", () -> Void, Cranelift, "Flush the stdout write buffer to the OS."),
    rt!("gos_rt_fs_create_dir_all", (Ptr) -> I64, Cranelift, "Create a directory and all parents; returns 0 on success."),
    rt!("gos_rt_fs_list_dir", (Ptr) -> Ptr, Cranelift, "List the entries in a directory as a GosVec<String>."),
    rt!("gos_rt_fs_read_to_string", (Ptr) -> Ptr, Cranelift, "Read an entire file into a String."),
    rt!("gos_rt_fs_walk_dir", (Ptr) -> Ptr, Cranelift, "Walk a directory tree and return all entry paths as a GosVec."),
    rt!("gos_rt_fs_write", (Ptr, Ptr) -> I64, Cranelift, "Write bytes to a file, creating or truncating it; returns 0 on success."),
    rt!("gos_rt_gc_alloc", (I64) -> Ptr, Both, "Allocate `size` bytes on the GC-managed heap; returns an opaque pointer."),
    rt!("gos_rt_gc_alloc_rooted", (I64) -> I32, Cranelift, "Allocate a GC-rooted slot and return its slot index."),
    rt!("gos_rt_gc_collect_with_stack_roots", () -> I64, Cranelift, "Trigger a full GC collection, scanning the shadow stack for roots."),
    rt!("gos_rt_gc_concurrent_finish", () -> I64, Cranelift, "Finish a concurrent GC cycle; returns bytes freed."),
    rt!("gos_rt_gc_concurrent_start", () -> Void, Cranelift, "Begin a concurrent GC marking phase."),
    rt!("gos_rt_gc_concurrent_step", (I64) -> I64, Cranelift, "Advance the concurrent GC by a bounded number of steps."),
    rt!("gos_rt_gc_deregister", (Ptr) -> Void, Cranelift, "Remove a heap allocation from the GC tracking registry."),
    rt!("gos_rt_gc_phase", () -> I32, Cranelift, "Return the current GC phase (idle=0, marking=1, sweeping=2)."),
    rt!("gos_rt_gc_reset", () -> Void, Cranelift, "Reset all GC-managed allocations (development/test helper)."),
    rt!("gos_rt_gc_shadow_push", (I32) -> Void, Cranelift, "Push a shadow-stack frame with N root slots."),
    rt!("gos_rt_gc_shadow_restore", (I64) -> Void, Cranelift, "Restore the shadow stack to a previously saved index."),
    rt!("gos_rt_gc_shadow_save", () -> I64, Cranelift, "Save and return the current shadow-stack depth."),
    rt!("gos_rt_go_spawn", (Ptr, Ptr) -> Void, Cranelift, "Spawn a goroutine with an env pointer and function pointer."),
    rt!("gos_rt_go_spawn_call_0", (Ptr) -> Void, Cranelift, "Spawn a zero-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_1", (Ptr, I64) -> Void, Cranelift, "Spawn a one-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_2", (Ptr, I64, I64) -> Void, Cranelift, "Spawn a two-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_3", (Ptr, I64, I64, I64) -> Void, Cranelift, "Spawn a three-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_4", (Ptr, I64, I64, I64, I64) -> Void, Cranelift, "Spawn a four-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_5", (Ptr, I64, I64, I64, I64, I64) -> Void, Cranelift, "Spawn a five-argument goroutine from a function pointer."),
    rt!("gos_rt_go_spawn_call_6", (Ptr, I64, I64, I64, I64, I64, I64) -> Void, Cranelift, "Spawn a six-argument goroutine from a function pointer."),
    rt!("gos_rt_go_yield", () -> Void, Both, "Yield the current goroutine, allowing other goroutines to run."),
    rt!("gos_rt_gzip_decode", (Ptr) -> Ptr, Cranelift, "Decompress a gzip-encoded byte string."),
    rt!("gos_rt_gzip_encode", (Ptr) -> Ptr, Cranelift, "Compress a string with gzip encoding."),
    rt!("gos_rt_heap_i64_free", (Ptr) -> Void, Cranelift, "Drop a HeapI64 array and release its memory."),
    rt!("gos_rt_heap_i64_get", (Ptr, I64) -> I64, Both, "Read the i64 at index `i` from a HeapI64 array."),
    rt!("gos_rt_heap_i64_len", (Ptr) -> I64, Cranelift, "Return the element count of a HeapI64 array."),
    rt!("gos_rt_heap_i64_new", (I64) -> Ptr, Both, "Allocate a HeapI64 array of the given capacity."),
    rt!("gos_rt_heap_i64_set", (Ptr, I64, I64) -> Void, Both, "Write an i64 at index `i` in a HeapI64 array."),
    rt!("gos_rt_heap_i64_write_bytes_to_stdout", (Ptr, I64, I64) -> Void, Cranelift, "Write bytes from a HeapI64 array directly to stdout."),
    rt!("gos_rt_heap_i64_write_lines_to_stdout", (Ptr, I64, I64, I64) -> Void, Cranelift, "Write lines from a HeapI64 array with a newline delimiter to stdout."),
    rt!("gos_rt_heap_u8_free", (Ptr) -> Void, Both, "Drop a HeapU8 byte array and release its memory."),
    rt!("gos_rt_heap_u8_get", (Ptr, I64) -> I64, Both, "Read the byte at index `i` from a HeapU8 array."),
    rt!("gos_rt_heap_u8_len", (Ptr) -> I64, Both, "Return the byte count of a HeapU8 array."),
    rt!("gos_rt_heap_u8_new", (I64) -> Ptr, Both, "Allocate a HeapU8 byte array of the given capacity."),
    rt!("gos_rt_heap_u8_set", (Ptr, I64, I64) -> Void, Both, "Write a byte at index `i` in a HeapU8 array."),
    rt!("gos_rt_heap_u8_to_string", (Ptr, I64) -> Ptr, Both, "Convert the first `len` bytes of a HeapU8 to a String."),
    rt!("gos_rt_heap_u8_write_bytes_to_stdout", (Ptr, I64, I64) -> Void, Both, "Write bytes from a HeapU8 array directly to stdout."),
    rt!("gos_rt_heap_u8_write_lines_to_stdout", (Ptr, I64, I64, I64) -> Void, Both, "Write lines from a HeapU8 array with a newline delimiter to stdout."),
    rt!("gos_rt_http2_bind_and_run_h2c", (Ptr, Ptr, I64) -> Void, Cranelift, "Start an HTTP/2 (h2c) server on the given address with the given handler."),
    rt!("gos_rt_http_client_get", (Ptr, Ptr) -> Ptr, Cranelift, "Perform an HTTP GET using a reusable client."),
    rt!("gos_rt_http_client_new", () -> Ptr, Cranelift, "Allocate a new HTTP client."),
    rt!("gos_rt_http_client_post", (Ptr, Ptr) -> Ptr, Cranelift, "Perform an HTTP POST using a reusable client."),
    rt!("gos_rt_http_get", (Ptr, Ptr) -> Ptr, Cranelift, "Perform a one-shot HTTP GET and return the response."),
    rt!("gos_rt_http_request_body", (Ptr, Ptr) -> Ptr, Cranelift, "Construct an HTTP request with the given method, URL, and body."),
    rt!("gos_rt_http_request_body_str", (Ptr) -> Ptr, Cranelift, "Return the body of an HTTP request as a String."),
    rt!("gos_rt_http_request_get_header", (Ptr, Ptr) -> Ptr, Cranelift, "Get the value of a named header from an HTTP request."),
    rt!("gos_rt_http_request_header", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Construct an HTTP request and set an initial header."),
    rt!("gos_rt_http_request_method", (Ptr) -> Ptr, Cranelift, "Return the HTTP method string of a request."),
    rt!("gos_rt_http_request_path", (Ptr) -> Ptr, Cranelift, "Return the URL path component of an HTTP request."),
    rt!("gos_rt_http_request_query", (Ptr) -> Ptr, Cranelift, "Return the query string of an HTTP request."),
    rt!("gos_rt_http_request_send", (Ptr) -> Ptr, Cranelift, "Execute an HTTP request and return the response."),
    rt!("gos_rt_http_request_set_header", (Ptr, Ptr, Ptr) -> Void, Cranelift, "Set a header on an HTTP request."),
    rt!("gos_rt_http_response_body", (Ptr) -> Ptr, Cranelift, "Return the body bytes of an HTTP response as a String."),
    rt!("gos_rt_http_response_get_header", (Ptr, Ptr) -> Ptr, Cranelift, "Get the value of a named header from an HTTP response."),
    rt!("gos_rt_http_response_json_new", (I64, Ptr) -> Ptr, Cranelift, "Construct an HTTP response with a JSON body and status code."),
    rt!("gos_rt_http_response_set_header", (Ptr, Ptr, Ptr) -> Void, Cranelift, "Set a header on an HTTP response."),
    rt!("gos_rt_http_response_status", (Ptr) -> I64, Cranelift, "Return the integer HTTP status code of a response."),
    rt!("gos_rt_http_response_text_new", (I64, Ptr) -> Ptr, Cranelift, "Construct an HTTP response with a text body and status code."),
    rt!("gos_rt_http_serve", (Ptr, Ptr, I64) -> Void, Cranelift, "Start an HTTP server on the given address with the given handler."),
    rt!("gos_rt_http_stream", (Ptr, Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Open a streaming HTTP connection and return a response stream."),
    rt!("gos_rt_http_stream_next_line", (Ptr) -> Ptr, Cranelift, "Read the next line from a streaming HTTP response."),
    rt!("gos_rt_i64_to_str", (I64) -> Ptr, Both, "Convert an i64 to its decimal string representation."),
    rt!("gos_rt_io_stderr", () -> Ptr, Both, "Return a pointer to the process stderr stream."),
    rt!("gos_rt_io_stdin", () -> Ptr, Both, "Return a pointer to the process stdin stream."),
    rt!("gos_rt_io_stdout", () -> Ptr, Both, "Return a pointer to the process stdout stream."),
    rt!("gos_rt_iter_all_i64", (Ptr, Ptr) -> I64, Both, "iter::all over Vec<i64>: returns 1 if every element satisfies the closure predicate."),
    rt!("gos_rt_iter_any_i64", (Ptr, Ptr) -> I64, Both, "iter::any over Vec<i64>: returns 1 if some element satisfies the closure predicate."),
    rt!("gos_rt_iter_chain_i64", (Ptr, Ptr) -> Ptr, Both, "iter::chain over Vec<i64>: returns a fresh Vec<i64> concatenating both inputs."),
    rt!("gos_rt_iter_count", (Ptr) -> I64, Both, "iter::count: return the element length of the input Vec."),
    rt!("gos_rt_iter_filter_i64", (Ptr, Ptr) -> Ptr, Both, "iter::filter over Vec<i64>: keep elements for which the closure returns nonzero."),
    rt!("gos_rt_iter_find_i64", (Ptr, Ptr) -> I64, Both, "iter::find over Vec<i64>: returns the first matching element (0 when none — pair with gos_rt_iter_find_i64_flag)."),
    rt!("gos_rt_iter_find_i64_flag", (Ptr, Ptr) -> I64, Both, "Companion flag for gos_rt_iter_find_i64: returns 1 when some element matched, 0 otherwise."),
    rt!("gos_rt_iter_fold_i64", (I64, Ptr, Ptr) -> I64, Both, "iter::fold over Vec<i64> with i64 accumulator and a (acc, x) -> acc closure."),
    rt!("gos_rt_iter_for_each_i64", (Ptr, Ptr) -> Void, Both, "iter::for_each over Vec<i64>: invokes the closure once per element."),
    rt!("gos_rt_iter_for_each_ptr", (Ptr, Ptr) -> Void, Both, "iter::for_each over Vec<*ptr> (Strings / aggregates): invokes the closure once per element."),
    rt!("gos_rt_iter_map_i64", (Ptr, Ptr) -> Ptr, Both, "iter::map over Vec<i64>: returns a fresh Vec<i64> of f(x)."),
    rt!("gos_rt_iter_max_i64", (Ptr) -> I64, Both, "iter::max over Vec<i64> (returns i64::MIN for empty input)."),
    rt!("gos_rt_iter_min_i64", (Ptr) -> I64, Both, "iter::min over Vec<i64> (returns i64::MIN for empty input)."),
    rt!("gos_rt_iter_product_f64", (Ptr) -> F64, Both, "iter::product over Vec<f64>."),
    rt!("gos_rt_iter_product_i64", (Ptr) -> I64, Both, "iter::product over Vec<i64> with wrapping multiplication."),
    rt!("gos_rt_iter_range", (I64, I64) -> Ptr, Both, "iter::range(start, end) -> Vec<i64> over [start, end)."),
    rt!("gos_rt_iter_range_inclusive", (I64, I64) -> Ptr, Both, "iter::range_inclusive(start, end) -> Vec<i64> over [start, end]."),
    rt!("gos_rt_iter_repeat_i64", (I64, I64) -> Ptr, Both, "iter::repeat(value, n) -> Vec<i64> filled with value."),
    rt!("gos_rt_iter_reversed_i64", (Ptr) -> Ptr, Both, "iter::reversed over Vec<i64>: returns a fresh reversed Vec."),
    rt!("gos_rt_iter_skip_i64", (I64, Ptr) -> Ptr, Both, "iter::skip(n, xs) -> Vec<i64> dropping the first n elements."),
    rt!("gos_rt_iter_sum_by_i64", (Ptr, Ptr) -> I64, Both, "iter::sum_by over Vec<i64>: sums the closure's returns across all elements."),
    rt!("gos_rt_iter_sum_f64", (Ptr) -> F64, Both, "iter::sum over Vec<f64>."),
    rt!("gos_rt_iter_sum_i64", (Ptr) -> I64, Both, "iter::sum over Vec<i64>."),
    rt!("gos_rt_iter_take_i64", (I64, Ptr) -> Ptr, Both, "iter::take(n, xs) -> Vec<i64> with the first n elements."),
    rt!("gos_rt_json_as_array_opt", (Ptr) -> Ptr, Cranelift, "Return the JSON value as an array, or null if it is not an array."),
    rt!("gos_rt_json_as_bool", (Ptr) -> I32, Cranelift, "Coerce a JSON value to a bool; panics if the value is not a boolean."),
    rt!("gos_rt_json_as_f64", (Ptr) -> F64, Cranelift, "Coerce a JSON value to f64; panics if not a number."),
    rt!("gos_rt_json_as_i64", (Ptr) -> I64, Cranelift, "Coerce a JSON value to i64; panics if not an integer."),
    rt!("gos_rt_json_as_str", (Ptr) -> Ptr, Cranelift, "Return the JSON string value; panics if not a string."),
    rt!("gos_rt_json_at", (Ptr, I64) -> Ptr, Cranelift, "Index into a JSON array by position."),
    rt!("gos_rt_json_display", (Ptr) -> Ptr, Cranelift, "Render a JSON value to a compact display string."),
    rt!("gos_rt_json_get", (Ptr, Ptr) -> Ptr, Cranelift, "Look up a key in a JSON object; panics if key absent."),
    rt!("gos_rt_json_get_opt", (Ptr, Ptr) -> Ptr, Cranelift, "Look up a key in a JSON object; returns null if key absent."),
    rt!("gos_rt_json_identity", (Ptr) -> Ptr, Cranelift, "Identity function for JSON values (used for type coercions)."),
    rt!("gos_rt_json_is_null", (Ptr) -> I32, Cranelift, "Return 1 if the JSON value is null, 0 otherwise."),
    rt!("gos_rt_json_keys_opt", (Ptr) -> Ptr, Cranelift, "Return the keys of a JSON object as a GosVec, or null if not an object."),
    rt!("gos_rt_json_len", (Ptr) -> I64, Cranelift, "Return the number of elements in a JSON array or object."),
    rt!("gos_rt_json_parse", (Ptr) -> Ptr, Cranelift, "Parse a JSON string into a GosJson value."),
    rt!("gos_rt_json_render", (Ptr) -> Ptr, Cranelift, "Serialize a GosJson value to a compact JSON string."),
    rt!("gos_rt_json_set", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Set a key on a JSON object and return the modified value."),
    rt!("gos_rt_json_value_array", (Ptr) -> Ptr, Cranelift, "Construct a JSON array value from a GosVec."),
    rt!("gos_rt_json_value_bool", (I32) -> Ptr, Cranelift, "Construct a JSON boolean value."),
    rt!("gos_rt_json_value_int", (I64) -> Ptr, Cranelift, "Construct a JSON integer value."),
    rt!("gos_rt_json_value_null", () -> Ptr, Cranelift, "Construct a JSON null value."),
    rt!("gos_rt_json_value_object", (Ptr) -> Ptr, Cranelift, "Construct a JSON object from a flat key-value GosVec."),
    rt!("gos_rt_json_value_object_n", (I64, Ptr) -> Ptr, Cranelift, "Construct a JSON object from N key-value pairs in a raw pointer."),
    rt!("gos_rt_json_value_string", (Ptr) -> Ptr, Cranelift, "Construct a JSON string value."),
    rt!("gos_rt_lcg_jump", (I64, I64, I64, I64, I64) -> I64, Both, "Advance an LCG state by N steps; returns the new state."),
    rt!("gos_rt_len", (Ptr) -> I64, Both, "Return the element count of a GosVec or the byte length of a String."),
    rt!("gos_rt_len_is_zero", (Ptr) -> I8, Cranelift, "Return 1 if a GosVec or string is empty, 0 otherwise."),
    rt!("gos_rt_main_exit_code", (I64) -> I32, Cranelift, "Translate the gos_main result value into a process exit code."),
    rt!("gos_rt_map_clear", (Ptr) -> Void, Cranelift, "Remove all entries from a GosMap."),
    rt!("gos_rt_map_contains_key_i64", (Ptr, I64) -> I8, Cranelift, "Return 1 if the map contains the given i64 key."),
    rt!("gos_rt_map_contains_key_str", (Ptr, Ptr) -> I8, Cranelift, "Return 1 if the map contains the given string key."),
    rt!("gos_rt_map_free", (Ptr) -> Void, Cranelift, "Drop a GosMap and release its memory."),
    rt!("gos_rt_map_get", (Ptr, Ptr, Ptr) -> I32, Cranelift, "Generic map get: writes the value to an out-pointer; returns 1 if present."),
    rt!("gos_rt_map_get_i64", (Ptr, I64) -> I64, Cranelift, "Get an i64 value by i64 key; returns 0 if absent."),
    rt!("gos_rt_map_get_i64_str", (Ptr, I64) -> Ptr, Cranelift, "Get a string value by i64 key; returns null if absent."),
    rt!("gos_rt_map_get_or_i64", (Ptr, I64, I64) -> I64, Cranelift, "Get an i64 value by i64 key, or a default if absent."),
    rt!("gos_rt_map_get_or_i64_str", (Ptr, I64, Ptr) -> Ptr, Cranelift, "Get a string value by i64 key, or a default string if absent."),
    rt!("gos_rt_map_get_or_str_i64", (Ptr, Ptr, I64) -> I64, Cranelift, "Get an i64 value by string key, or a default if absent."),
    rt!("gos_rt_map_get_or_str_str", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Get a string value by string key, or a default string if absent."),
    rt!("gos_rt_map_get_str_i64", (Ptr, Ptr) -> I64, Cranelift, "Get an i64 value by string key; returns 0 if absent."),
    rt!("gos_rt_map_get_str_str", (Ptr, Ptr) -> Ptr, Cranelift, "Get a string value by string key; returns null if absent."),
    rt!("gos_rt_map_inc_at_str_i64", (Ptr, Ptr, I64, I64, I64) -> I64, Cranelift, "Increment or insert-with-default the i64 at a string key; returns new value."),
    rt!("gos_rt_map_inc_i64", (Ptr, I64, I64) -> I64, Cranelift, "Increment the i64 at an i64 key by a given amount."),
    rt!("gos_rt_map_inc_str_i64", (Ptr, Ptr, I64) -> I64, Cranelift, "Increment the i64 at a string key by a given amount."),
    rt!("gos_rt_map_insert", (Ptr, Ptr, Ptr) -> Void, Cranelift, "Generic raw-pointer map insert; prefer typed variants for new code."),
    rt!("gos_rt_map_insert_i64_i64", (Ptr, I64, I64) -> Void, Cranelift, "Insert or update an i64-to-i64 entry."),
    rt!("gos_rt_map_insert_i64_str", (Ptr, I64, Ptr) -> Void, Cranelift, "Insert or update an i64-to-String entry."),
    rt!("gos_rt_map_insert_str_i64", (Ptr, Ptr, I64) -> Void, Cranelift, "Insert or update a String-to-i64 entry."),
    rt!("gos_rt_map_insert_str_str", (Ptr, Ptr, Ptr) -> Void, Cranelift, "Insert or update a String-to-String entry."),
    rt!("gos_rt_map_keys_i64", (Ptr) -> Ptr, Cranelift, "Return all i64 keys of a GosMap as a GosVec."),
    rt!("gos_rt_map_keys_str", (Ptr) -> Ptr, Cranelift, "Return all string keys of a GosMap as a GosVec."),
    rt!("gos_rt_map_len", (Ptr) -> I64, Cranelift, "Return the number of entries in a GosMap."),
    rt!("gos_rt_map_new", (I32, I32) -> Ptr, Cranelift, "Allocate an empty GosMap with given key and value type tags."),
    rt!("gos_rt_map_new_with_capacity", (I32, I32, I64) -> Ptr, Cranelift, "Allocate a GosMap with a pre-reserved capacity."),
    rt!("gos_rt_map_or_insert_i64_i64", (Ptr, I64, I64) -> I64, Cranelift, "Insert the default i64 at an i64 key if absent; return the value."),
    rt!("gos_rt_map_or_insert_str_i64", (Ptr, Ptr, I64) -> I64, Cranelift, "Insert the default i64 at a string key if absent; return the value."),
    rt!("gos_rt_map_remove", (Ptr, Ptr) -> I32, Cranelift, "Generic map remove; returns 1 if the key was present."),
    rt!("gos_rt_map_remove_i64", (Ptr, I64) -> I8, Cranelift, "Remove an i64 key from the map; returns 1 if it was present."),
    rt!("gos_rt_map_remove_str", (Ptr, Ptr) -> I8, Cranelift, "Remove a string key from the map; returns 1 if it was present."),
    rt!("gos_rt_map_values_i64", (Ptr) -> Ptr, Cranelift, "Return all i64 values of a GosMap as a GosVec."),
    rt!("gos_rt_map_values_str", (Ptr) -> Ptr, Cranelift, "Return all string values of a GosMap as a GosVec."),
    rt!("gos_rt_math_abs", (F64) -> F64, Both, "Compute the absolute value of an f64."),
    rt!("gos_rt_math_ceil", (F64) -> F64, Both, "Round an f64 up to the nearest integer."),
    rt!("gos_rt_math_cos", (F64) -> F64, Both, "Compute the cosine of an angle in radians."),
    rt!("gos_rt_math_exp", (F64) -> F64, Both, "Compute e raised to the power of an f64."),
    rt!("gos_rt_math_floor", (F64) -> F64, Both, "Round an f64 down to the nearest integer."),
    rt!("gos_rt_math_log", (F64) -> F64, Both, "Compute the natural logarithm of an f64."),
    rt!("gos_rt_math_pow", (F64, F64) -> F64, Both, "Raise an f64 base to an f64 exponent."),
    rt!("gos_rt_math_sin", (F64) -> F64, Both, "Compute the sine of an angle in radians."),
    rt!("gos_rt_math_sqrt", (F64) -> F64, Both, "Compute the non-negative square root of an f64."),
    rt!("gos_rt_mutex_lock", (Ptr) -> Void, Cranelift, "Acquire a Mutex; blocks until the lock is available."),
    rt!("gos_rt_mutex_new", () -> Ptr, Both, "Allocate and initialise a new Mutex."),
    rt!("gos_rt_mutex_unlock", (Ptr) -> Void, Cranelift, "Release a previously acquired Mutex."),
    rt!("gos_rt_mw_accepts_gzip", (Ptr) -> I32, Cranelift, "Return 1 if the Accept-Encoding header advertises gzip support."),
    rt!("gos_rt_mw_new_request_id", () -> Ptr, Cranelift, "Generate a process-monotonic request-id string."),
    rt!("gos_rt_native_client_get", (Ptr, Ptr) -> Ptr, Cranelift, "Issue a one-shot GET via a NativeClient handle."),
    rt!("gos_rt_native_client_new", () -> Ptr, Cranelift, "Allocate a NativeClient handle."),
    rt!("gos_rt_nested_arr_to_vec", (I64, I64, Ptr, I64) -> Ptr, Cranelift, "Flatten a nested fixed-size array into a GosVec."),
    rt!("gos_rt_now_ns", () -> I64, Both, "Return the current monotonic time in nanoseconds."),
    rt!("gos_rt_option_default_i64", (I64, Ptr) -> I64, Both, "option::default(v, opt) over Option<i64>: returns inner if Some, fallback if None."),
    rt!("gos_rt_option_is_none", (Ptr) -> I64, Both, "option::is_none — 1 if opt is None, 0 if Some."),
    rt!("gos_rt_option_is_some", (Ptr) -> I64, Both, "option::is_some — 1 if opt is Some, 0 if None."),
    rt!("gos_rt_os_args", () -> Ptr, Both, "Return the process argument list as a GosVec<String>."),
    rt!("gos_rt_os_cwd", () -> Ptr, Cranelift, "Return the current working directory as a String."),
    rt!("gos_rt_os_env", (Ptr) -> Ptr, Cranelift, "Return the value of an environment variable, or null if not set."),
    rt!("gos_rt_os_exists", (Ptr) -> I64, Cranelift, "Return 1 if the path exists on the filesystem, 0 otherwise."),
    rt!("gos_rt_os_file_size", (Ptr) -> I64, Cranelift, "Return the file size in bytes, or 0 if the path cannot be stat'd."),
    rt!("gos_rt_os_is_dir", (Ptr) -> I64, Cranelift, "Return 1 if the path is a directory, 0 otherwise."),
    rt!("gos_rt_os_is_file", (Ptr) -> I64, Cranelift, "Return 1 if the path is a regular file, 0 otherwise."),
    rt!("gos_rt_os_is_symlink", (Ptr) -> I64, Cranelift, "Return 1 if the path is a symbolic link, 0 otherwise."),
    rt!("gos_rt_os_mkdir_all_result", (Ptr) -> Ptr, Cranelift, "Create a directory tree; returns an error Result on failure."),
    rt!("gos_rt_os_read_dir", (Ptr) -> Ptr, Cranelift, "List directory entries as a GosVec<String>."),
    rt!("gos_rt_os_remove_dir_all_result", (Ptr) -> Ptr, Cranelift, "Remove a directory tree; returns an error Result on failure."),
    rt!("gos_rt_os_remove_file", (Ptr) -> I64, Cranelift, "Remove a file; returns 0 on success."),
    rt!("gos_rt_os_remove_file_result", (Ptr) -> Ptr, Cranelift, "Remove a file; returns an error Result on failure."),
    rt!("gos_rt_os_set_env", (Ptr, Ptr) -> Ptr, Cranelift, "Set an environment variable; returns an error Result on failure."),
    rt!("gos_rt_os_unset_env", (Ptr) -> Void, Cranelift, "Unset an environment variable."),
    rt!("gos_rt_os_write_file_result", (Ptr, Ptr) -> Ptr, Cranelift, "Write bytes to a file; returns an error Result on failure."),
    rt!("gos_rt_panic", (Ptr) -> Void, Both, "Abort the current goroutine with a message string."),
    rt!("gos_rt_parse_f64", (Ptr, Ptr) -> F64, Cranelift, "Parse a string as an f64; second arg is the default on error."),
    rt!("gos_rt_parse_i64", (Ptr, Ptr) -> I64, Cranelift, "Parse a string as an i64; second arg is the default on error."),
    rt!("gos_rt_parse_i64_result", (Ptr) -> Ptr, Cranelift, "Parse a string as an i64; returns an error Result on failure."),
    rt!("gos_rt_path_join", (Ptr, Ptr) -> Ptr, Cranelift, "Join two path strings with the OS separator."),
    rt!("gos_rt_preempt_check", () -> I32, Cranelift, "Check whether a preemption point should yield; returns 1 if so."),
    rt!("gos_rt_preempt_check_and_yield", () -> I32, Cranelift, "Preempt-check and yield in one call."),
    rt!("gos_rt_print_bool", (I32) -> Void, Both, "Print a bool to stdout within the current stdout lock."),
    rt!("gos_rt_print_char", (I32) -> Void, Both, "Print a char to stdout within the current stdout lock."),
    rt!("gos_rt_print_f64", (F64) -> Void, Both, "Print an f64 to stdout within the current stdout lock."),
    rt!("gos_rt_print_i64", (I64) -> Void, Both, "Print an i64 to stdout within the current stdout lock."),
    rt!("gos_rt_print_str", (Ptr) -> Void, Both, "Print a string to stdout within the current stdout lock."),
    rt!("gos_rt_print_u64", (I64) -> Void, Both, "Print a u64 to stdout within the current stdout lock."),
    rt!("gos_rt_println", () -> Void, Both, "Print a newline to stdout within the current stdout lock."),
    rt!("gos_rt_process_abort", () -> Void, Both, "Abort the current process without unwinding."),
    rt!("gos_rt_process_id", () -> I32, Both, "Return the current process ID."),
    rt!("gos_rt_proxy_forward", (Ptr, Ptr) -> Ptr, Cranelift, "Forward an incoming request through a Proxy handle to its upstream."),
    rt!("gos_rt_proxy_new", (Ptr) -> Ptr, Cranelift, "Allocate a Proxy handle pointing at a fixed upstream URL."),
    rt!("gos_rt_regex_captures", (Ptr, Ptr) -> Ptr, Cranelift, "Return all capture groups for the first match of a regex."),
    rt!("gos_rt_regex_captures_all", (Ptr, Ptr) -> Ptr, Cranelift, "Return all capture groups for every match of a regex."),
    rt!("gos_rt_regex_compile", (Ptr) -> Ptr, Cranelift, "Compile a regex pattern string into a Regex object."),
    rt!("gos_rt_regex_find", (Ptr, Ptr) -> Ptr, Cranelift, "Return the first match of a regex as a string."),
    rt!("gos_rt_regex_find_all", (Ptr, Ptr) -> Ptr, Cranelift, "Return all matches of a regex as a GosVec."),
    rt!("gos_rt_regex_find_opt", (Ptr, Ptr) -> Ptr, Cranelift, "Return the first match of a regex, or null if no match."),
    rt!("gos_rt_regex_is_match", (Ptr, Ptr) -> I8, Cranelift, "Return 1 if the regex matches anywhere in the string."),
    rt!("gos_rt_regex_replace", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Replace the first regex match with a replacement string."),
    rt!("gos_rt_regex_replace_all", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Replace all regex matches with a replacement string."),
    rt!("gos_rt_regex_split", (Ptr, Ptr) -> Ptr, Cranelift, "Split a string on a regex pattern."),
    rt!("gos_rt_result_dbg", (I64) -> I64, Cranelift, "Print a debug representation of a Result discriminant."),
    rt!("gos_rt_result_disc", (Ptr) -> I64, Cranelift, "Return the discriminant of a Result (0=Ok, 1=Err)."),
    rt!("gos_rt_result_err", (Ptr) -> I64, Cranelift, "Unwrap the Err payload of a Result; panics if Ok."),
    rt!("gos_rt_result_is_err", (Ptr) -> I64, Cranelift, "Return 1 if the Result is Err, 0 if Ok."),
    rt!("gos_rt_result_is_ok", (Ptr) -> I64, Cranelift, "Return 1 if the Result is Ok, 0 if Err."),
    rt!("gos_rt_result_map", (Ptr, Ptr) -> Ptr, Cranelift, "Apply a function pointer to the Ok payload of a Result."),
    rt!("gos_rt_result_map_bare", (Ptr, I64) -> Ptr, Cranelift, "Replace the Ok payload with a bare i64 value."),
    rt!("gos_rt_result_map_err", (Ptr, Ptr) -> Ptr, Cranelift, "Apply a function pointer to the Err payload of a Result."),
    rt!("gos_rt_result_map_err_bare", (Ptr, I64) -> Ptr, Cranelift, "Replace the Err payload with a bare i64 value."),
    rt!("gos_rt_result_new", (I64, I64) -> Ptr, Cranelift, "Construct a new Result from a discriminant and payload."),
    rt!("gos_rt_result_ok", (Ptr) -> I64, Cranelift, "Unwrap the Ok payload of a Result; panics if Err."),
    rt!("gos_rt_result_ok_or", (Ptr, I64) -> Ptr, Cranelift, "Unwrap the Ok payload, or return a default i64 if Err."),
    rt!("gos_rt_result_payload", (Ptr) -> I64, Cranelift, "Return the raw i64 payload of a Result without discriminant check."),
    rt!("gos_rt_result_unwrap", (Ptr) -> I64, Cranelift, "Unwrap a Result's Ok payload; panics with a message if Err."),
    rt!("gos_rt_result_unwrap_or", (Ptr, I64) -> I64, Cranelift, "Unwrap a Result's Ok payload, or return the default if Err."),
    rt!("gos_rt_router_add", (Ptr, Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a route on a Router: (method, pattern, handler-env, fn-addr)."),
    rt!("gos_rt_router_delete", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a DELETE route on a Router."),
    rt!("gos_rt_router_get", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a GET route on a Router."),
    rt!("gos_rt_router_head", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a HEAD route on a Router."),
    rt!("gos_rt_router_new", () -> Ptr, Cranelift, "Allocate a Router handle."),
    rt!("gos_rt_router_options", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register an OPTIONS route on a Router."),
    rt!("gos_rt_router_patch", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a PATCH route on a Router."),
    rt!("gos_rt_router_post", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a POST route on a Router."),
    rt!("gos_rt_router_put", (Ptr, Ptr, Ptr, I64) -> Void, Cranelift, "Register a PUT route on a Router."),
    rt!("gos_rt_router_serve", (Ptr, Ptr) -> Ptr, Cranelift, "Dispatch a request through a Router's route table."),
    rt!("gos_rt_set_args", (I32, Ptr) -> Void, Cranelift, "Register the process argc/argv with the runtime."),
    rt!("gos_rt_set_contains", (Ptr, Ptr) -> I8, Cranelift, "Return 1 if a HashSet contains the given element."),
    rt!("gos_rt_set_free", (Ptr) -> Void, Cranelift, "Drop a HashSet and release its memory."),
    rt!("gos_rt_set_insert", (Ptr, Ptr) -> I8, Cranelift, "Insert an element into a HashSet; returns 1 if it was new."),
    rt!("gos_rt_set_len", (Ptr) -> I64, Cranelift, "Return the number of elements in a HashSet."),
    rt!("gos_rt_set_new", () -> Ptr, Cranelift, "Allocate an empty HashSet."),
    rt!("gos_rt_set_remove", (Ptr, Ptr) -> I8, Cranelift, "Remove an element from a HashSet; returns 1 if it was present."),
    rt!("gos_rt_sleep_ms", (I64) -> Void, Both, "Sleep the current goroutine for at least the given number of milliseconds."),
    rt!("gos_rt_sleep_ns", (I64) -> Void, Cranelift, "Sleep the current goroutine for at least the given number of nanoseconds."),
    rt!("gos_rt_slog_debug", (Ptr) -> Void, Cranelift, "Emit a debug-level structured log line."),
    rt!("gos_rt_slog_error", (Ptr) -> Void, Cranelift, "Emit an error-level structured log line."),
    rt!("gos_rt_slog_info", (Ptr) -> Void, Cranelift, "Emit an info-level structured log line."),
    rt!("gos_rt_slog_warn", (Ptr) -> Void, Cranelift, "Emit a warning-level structured log line."),
    rt!("gos_rt_sse_encode_comment", (Ptr) -> Ptr, Cranelift, "Render a `:`-prefixed SSE keepalive comment line."),
    rt!("gos_rt_sse_encode_event", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Render one SSE event block with optional event name and id."),
    rt!("gos_rt_sse_encode_retry", (I64) -> Ptr, Cranelift, "Render an SSE retry directive in milliseconds."),
    rt!("gos_rt_static_mime_for_path", (Ptr) -> Ptr, Cranelift, "Guess a MIME type from a file path's extension."),
    rt!("gos_rt_stdout_acquire", () -> Void, Both, "Acquire the stdout lock; call before a sequence of print calls."),
    rt!("gos_rt_stdout_release", () -> Void, Both, "Release the stdout lock; call after a sequence of print calls."),
    rt!("gos_rt_str_as_bytes", (Ptr) -> Ptr, Cranelift, "Return the raw byte data of a String as a HeapU8."),
    rt!("gos_rt_str_byte_at", (Ptr, I64) -> I64, Both, "Return the byte value at the given index in a String."),
    rt!("gos_rt_str_compare", (Ptr, Ptr) -> I32, Both, "Compare two strings lexicographically; returns negative, 0, or positive."),
    rt!("gos_rt_str_concat", (Ptr, Ptr) -> Ptr, Both, "Concatenate two strings and return the result."),
    rt!("gos_rt_str_contains", (Ptr, Ptr) -> I32, Cranelift, "Return 1 if the string contains the given substring."),
    rt!("gos_rt_str_ends_with", (Ptr, Ptr) -> I32, Cranelift, "Return 1 if the string ends with the given suffix."),
    rt!("gos_rt_str_eq", (Ptr, Ptr) -> I8, Cranelift, "Return 1 if two strings are equal."),
    rt!("gos_rt_str_find", (Ptr, Ptr) -> I64, Cranelift, "Return the byte index of the first occurrence of a substring, or -1."),
    rt!("gos_rt_str_find_opt", (Ptr, Ptr) -> Ptr, Cranelift, "Return an Option<i64> of the byte index of the first substring match."),
    rt!("gos_rt_str_free", (Ptr) -> Void, Both, "Drop a String allocated by the runtime and release its memory."),
    rt!("gos_rt_str_is_empty", (Ptr) -> I8, Cranelift, "Return 1 if the string has zero bytes."),
    rt!("gos_rt_str_len", (Ptr) -> I64, Both, "Return the byte length of a String."),
    rt!("gos_rt_str_lines", (Ptr) -> Ptr, Cranelift, "Split a string into lines and return them as a GosVec."),
    rt!("gos_rt_str_repeat", (Ptr, I64) -> Ptr, Cranelift, "Repeat a string N times and return the result."),
    rt!("gos_rt_str_replace", (Ptr, Ptr, Ptr) -> Ptr, Cranelift, "Replace the first occurrence of a pattern in a string."),
    rt!("gos_rt_str_split", (Ptr, Ptr) -> Ptr, Cranelift, "Split a string by a delimiter and return a GosVec of parts."),
    rt!("gos_rt_str_starts_with", (Ptr, Ptr) -> I32, Cranelift, "Return 1 if the string starts with the given prefix."),
    rt!("gos_rt_str_substring", (Ptr, I64, I64) -> Ptr, Cranelift, "Return the substring from byte index `a` inclusive to `b` exclusive."),
    rt!("gos_rt_str_to_lower", (Ptr) -> Ptr, Cranelift, "Convert all ASCII characters in a string to lower case."),
    rt!("gos_rt_str_to_upper", (Ptr) -> Ptr, Cranelift, "Convert all ASCII characters in a string to upper case."),
    rt!("gos_rt_str_trim", (Ptr) -> Ptr, Cranelift, "Strip leading and trailing whitespace from a string."),
    rt!("gos_rt_stream_flush", (Ptr) -> Void, Cranelift, "Flush a writable stream to the OS."),
    rt!("gos_rt_stream_read_line", (Ptr) -> Ptr, Cranelift, "Read one line from a stream, stripping the trailing newline."),
    rt!("gos_rt_stream_read_to_string", (Ptr) -> Ptr, Cranelift, "Read all remaining bytes from a stream into a String."),
    rt!("gos_rt_stream_write_byte", (Ptr, I64) -> Void, Both, "Write a single byte to a stream."),
    rt!("gos_rt_stream_write_byte_array", (Ptr, Ptr, I64) -> Void, Both, "Write a slice of bytes to a stream."),
    rt!("gos_rt_stream_write_str", (Ptr, Ptr) -> Void, Cranelift, "Write a string to a stream."),
    rt!("gos_rt_sync_i64_add", (Ptr, I64, I64) -> I64, Cranelift, "Append an i64 to a shared sync Vec and return the new length."),
    rt!("gos_rt_sync_i64_drop", (Ptr) -> Void, Cranelift, "Drop a sync i64 Vec and release its memory."),
    rt!("gos_rt_sync_i64_get", (Ptr, I64) -> I64, Cranelift, "Read the i64 at index `i` from a sync i64 Vec."),
    rt!("gos_rt_sync_i64_len", (Ptr) -> I64, Cranelift, "Return the element count of a sync i64 Vec."),
    rt!("gos_rt_sync_i64_new", (I64) -> Ptr, Cranelift, "Allocate a sync i64 Vec with the given initial capacity."),
    rt!("gos_rt_sync_i64_push", (Ptr, I64) -> Void, Cranelift, "Append an i64 to a sync i64 Vec."),
    rt!("gos_rt_sync_i64_set", (Ptr, I64, I64) -> Void, Cranelift, "Write an i64 at index `i` in a sync i64 Vec."),
    rt!("gos_rt_sync_u8_drop", (Ptr) -> Void, Cranelift, "Drop a sync u8 Vec and release its memory."),
    rt!("gos_rt_sync_u8_get", (Ptr, I64) -> I64, Cranelift, "Read the byte at index `i` from a sync u8 Vec."),
    rt!("gos_rt_sync_u8_len", (Ptr) -> I64, Cranelift, "Return the byte count of a sync u8 Vec."),
    rt!("gos_rt_sync_u8_new", (I64) -> Ptr, Cranelift, "Allocate a sync u8 Vec with the given initial capacity."),
    rt!("gos_rt_sync_u8_push", (Ptr, I64) -> Void, Cranelift, "Append a byte to a sync u8 Vec."),
    rt!("gos_rt_sync_u8_set", (Ptr, I64, I64) -> Void, Cranelift, "Write a byte at index `i` in a sync u8 Vec."),
    rt!("gos_rt_testing_check", (I8, Ptr) -> I8, Cranelift, "Assert a bool condition in a test; records a failure if false."),
    rt!("gos_rt_testing_check_eq_i64", (I64, I64, Ptr) -> I8, Cranelift, "Assert two i64 values are equal in a test."),
    rt!("gos_rt_time_format_rfc3339", (I64) -> Ptr, Cranelift, "Format a Unix timestamp as an RFC 3339 date-time string."),
    rt!("gos_rt_time_now", () -> F64, Both, "Return the current wall-clock time as an f64 Unix timestamp."),
    rt!("gos_rt_time_now_ms", () -> I64, Both, "Return the current wall-clock time in milliseconds since epoch."),
    rt!("gos_rt_u64_to_str", (I64) -> Ptr, Both, "Convert a u64 to its decimal string representation."),
    rt!("gos_rt_vec_clone", (Ptr) -> Ptr, Cranelift, "Clone a GosVec, sharing a reference to its element data."),
    rt!("gos_rt_vec_format_bool", (Ptr) -> Ptr, Cranelift, "Format a GosVec<bool> as a debug string."),
    rt!("gos_rt_vec_format_f64", (Ptr) -> Ptr, Cranelift, "Format a GosVec<f64> as a debug string."),
    rt!("gos_rt_vec_format_i64", (Ptr) -> Ptr, Cranelift, "Format a GosVec<i64> as a debug string."),
    rt!("gos_rt_vec_format_string", (Ptr) -> Ptr, Cranelift, "Format a GosVec<String> as a debug string."),
    rt!("gos_rt_vec_format_vec_i64", (Ptr) -> Ptr, Cranelift, "Format a GosVec<Vec<i64>> as a debug string."),
    rt!("gos_rt_vec_free", (Ptr) -> Void, Cranelift, "Drop a GosVec and release its memory."),
    rt!("gos_rt_vec_from_arr", (I32, Ptr, I64) -> Ptr, Cranelift, "Construct a GosVec from a raw element array with type tag and length."),
    rt!("gos_rt_vec_get_i64", (Ptr, I64) -> I64, Cranelift, "Read the i64 at index `i` from a GosVec."),
    rt!("gos_rt_vec_get_ptr", (Ptr, I64) -> Ptr, Cranelift, "Read the pointer at index `i` from a GosVec."),
    rt!("gos_rt_vec_len", (Ptr) -> I64, Cranelift, "Return the number of elements in a GosVec."),
    rt!("gos_rt_vec_new", (I32) -> Ptr, Cranelift, "Allocate an empty GosVec with a given element type tag."),
    rt!("gos_rt_vec_pop", (Ptr, Ptr) -> I32, Cranelift, "Remove and return the last element of a GosVec."),
    rt!("gos_rt_vec_push", (Ptr, Ptr) -> Void, Both, "Append a pointer-sized element to a GosVec."),
    rt!("gos_rt_vec_push_i64", (Ptr, I64) -> Void, Cranelift, "Append an i64 to a GosVec."),
    rt!("gos_rt_vec_set_i64", (Ptr, I64, I64) -> Void, Cranelift, "Write an i64 at index `i` in a GosVec."),
    rt!("gos_rt_vec_slice", (Ptr, I64, I64) -> Ptr, Cranelift, "Return a sub-slice of a GosVec as a new GosVec."),
    rt!("gos_rt_vec_sort_by_aggr", (Ptr, Ptr) -> Void, Cranelift, "Sort a GosVec of multi-slot aggregate elements; comparator receives element pointers (stride read from vec.elem_bytes)."),
    rt!("gos_rt_vec_sort_by_i64", (Ptr, Ptr) -> Void, Cranelift, "Sort a GosVec by an i64-valued comparator closure."),
    rt!("gos_rt_vec_with_capacity", (I32, I64) -> Ptr, Cranelift, "Allocate a GosVec with a pre-reserved capacity."),
    rt!("gos_rt_wg_add", (Ptr, I64) -> I64, Cranelift, "Increment the WaitGroup counter by N."),
    rt!("gos_rt_wg_done", (Ptr) -> I64, Cranelift, "Decrement the WaitGroup counter by 1."),
    rt!("gos_rt_wg_error", (Ptr) -> I64, Cranelift, "Return 1 if any goroutine panicked while this WaitGroup was active."),
    rt!("gos_rt_wg_error_clear", (Ptr) -> I64, Cranelift, "Clear the error state of a WaitGroup."),
    rt!("gos_rt_wg_new", () -> Ptr, Both, "Allocate and initialise a new WaitGroup."),
    rt!("gos_rt_wg_wait", (Ptr) -> Void, Cranelift, "Block until the WaitGroup counter reaches zero."),
    rt!("gos_rt_write_barrier", (I32) -> Void, Llvm, "Notify the GC write barrier after a heap pointer store."),
    rt!("gos_rt_ws_accept_key", (Ptr) -> Ptr, Cranelift, "Compute the RFC 6455 Sec-WebSocket-Accept value from a client nonce."),
    rt!("gos_rt_ws_frame_text", (Ptr) -> Ptr, Cranelift, "Encode a UTF-8 string as one RFC 6455 text frame (server-side outbound)."),
];

/// Look up a runtime symbol by exact name.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static RuntimeEntry> {
    REGISTRY.iter().find(|e| e.name == name)
}

/// Produce all LLVM `declare` strings from the registry.
/// Replaces the raw `RUNTIME_DECLARATIONS` constant in `emit.rs`.
#[must_use]
pub fn all_llvm_declarations() -> Vec<String> {
    REGISTRY.iter().map(RuntimeEntry::llvm_declare).collect()
}
