//! Path-resolution + filesystem helpers shared by every subcommand.
//!
//! Centralising these here keeps `main.rs` minimal and gives every
//! subcommand the same project-root / source-discovery behaviour.

use std::fs;
use std::io::IsTerminal;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};

/// `true` when ANSI colour escapes should be written to stderr.
/// Honours `NO_COLOR` and `CLICOLOR=0`; otherwise tests for a TTY.
pub(crate) fn stderr_supports_colour() -> bool {
    if std::env::var_os("NO_COLOR").is_some() {
        return false;
    }
    if matches!(std::env::var("CLICOLOR").as_deref(), Ok("0")) {
        return false;
    }
    std::io::stderr().is_terminal()
}

/// Reads `file` (after `.gos`-resolution) into a `String`. Wraps
/// the OS error in [`friendly_io_error`] so the diagnostic stream
/// stays free of libc artefacts.
pub(crate) fn read_source(file: &PathBuf) -> Result<String> {
    let resolved = resolve_gos_source(file);
    fs::read_to_string(&resolved).map_err(|err| friendly_io_error(err, &resolved))
}

/// Renders a `std::io::Error` as a clean diagnostic free of
/// libc artefacts (`(os error N)` tails, `stat`/`reading`
/// syscall prefixes). Path-aware where a path is available.
pub(crate) fn friendly_io_error(err: std::io::Error, path: &Path) -> anyhow::Error {
    use std::io::ErrorKind;
    let display = path.display();
    let msg = match err.kind() {
        ErrorKind::NotFound => format!("file not found: {display}"),
        ErrorKind::PermissionDenied => format!("permission denied: {display}"),
        ErrorKind::IsADirectory => format!("expected a file, found a directory: {display}"),
        ErrorKind::NotADirectory => format!("expected a directory, found a file: {display}"),
        ErrorKind::AlreadyExists => format!("already exists: {display}"),
        ErrorKind::InvalidData => format!("invalid file contents: {display}"),
        ErrorKind::TimedOut => format!("timed out reading {display}"),
        ErrorKind::WriteZero => format!("could not write to {display}"),
        // Other (genuinely surprising) errors keep the kind name
        // so the user has something to grep for, but still drop
        // the libc `(os error N)` tail that std prepends.
        kind => format!("{display}: {kind:?}"),
    };
    anyhow!(msg)
}

/// When `path` is a shell launcher script (starts with `#!`) or has no
/// `.gos` extension but `path.gos` exists, returns the `.gos` file.
/// This prevents `gos run examples/get_xkcd` from trying to parse the
/// launcher script generated by `gos build`.
pub(crate) fn resolve_gos_source(path: &PathBuf) -> PathBuf {
    if path.extension().and_then(|s| s.to_str()) != Some("gos") {
        let with_ext = path.with_extension("gos");
        if with_ext.exists() {
            return with_ext;
        }
    }
    if let Ok(text) = fs::read_to_string(path) {
        if text.starts_with("#!") {
            let with_ext = path.with_extension("gos");
            if with_ext.exists() {
                return with_ext;
            }
        }
    }
    path.clone()
}

/// Walks up from the cwd looking for the nearest `project.toml`.
/// Returns the directory that contains it (the project root).
pub(crate) fn find_project_root() -> Option<PathBuf> {
    let cwd = std::env::current_dir().ok()?;
    let mut cursor: &Path = &cwd;
    loop {
        if cursor.join("project.toml").is_file() {
            return Some(cursor.to_path_buf());
        }
        let parent = cursor.parent()?;
        cursor = parent;
    }
}

/// Default source root for whole-project commands (`check`, `lint`,
/// `test`): the project root's `src/` if present, otherwise the
/// project root itself, otherwise the current directory.
pub(crate) fn default_test_root() -> Result<PathBuf> {
    if let Some(root) = find_project_root() {
        let src = root.join("src");
        if src.is_dir() {
            return Ok(src);
        }
        return Ok(root);
    }
    std::env::current_dir().context("read current directory")
}

/// Default entry point for whole-project run/build commands. Picks
/// `<project-root>/src/main.gos` when reachable; returns `Err`
/// otherwise so the caller can surface a useful diagnostic.
pub(crate) fn default_main_entry() -> Result<PathBuf> {
    let root = find_project_root().ok_or_else(|| {
        anyhow!(
            "no project.toml found above the current directory; pass a path or run from inside a project"
        )
    })?;
    let candidate = root.join("src").join("main.gos");
    if candidate.is_file() {
        return Ok(candidate);
    }
    let bare = root.join("main.gos");
    if bare.is_file() {
        return Ok(bare);
    }
    Err(anyhow!(
        "project root {} has no src/main.gos (or main.gos); pass a path explicitly",
        root.display()
    ))
}

/// Recursively gathers every `.gos` file under `root`. If `root`
/// names a single file, returns it as a one-element list.
pub(crate) fn collect_lint_targets(root: &PathBuf) -> Result<Vec<PathBuf>> {
    let meta = fs::metadata(root).map_err(|e| friendly_io_error(e, root))?;
    if meta.is_file() {
        return Ok(vec![root.clone()]);
    }
    let mut out = Vec::new();
    let mut stack = vec![root.clone()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).with_context(|| format!("read_dir {}", dir.display()))? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().and_then(|s| s.to_str()) == Some("gos") {
                out.push(path);
            }
        }
    }
    out.sort();
    Ok(out)
}

/// Picks the default binary name for a build, matching Rust's
/// `cargo build` rule: derive from the package name, not the
/// source filename. When the source sits inside a project (a
/// `project.toml` is found by walking parents), the binary takes
/// the last `/`-separated segment of `[project] id`. Loose-file
/// builds with no manifest fall back to the source stem.
pub(crate) fn default_unit_name(file: &Path) -> String {
    if let Some(manifest_path) = gossamer_pkg::find_manifest(file)
        && let Ok(text) = fs::read_to_string(&manifest_path)
        && let Ok(manifest) = gossamer_pkg::Manifest::parse(&text)
    {
        return manifest.project.id.tail().to_string();
    }
    file.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("main")
        .to_string()
}

/// Resolves the build output path.
///
/// Resolution order (first hit wins):
/// 1. `project.output` in the nearest enclosing `project.toml`
///    (relative paths resolve against the manifest's directory).
/// 2. `<project-root>/target/{debug,release}/<unit>`.
/// 3. `<source-dir>/target/{debug,release}/<unit>` for loose-file
///    builds with no manifest.
pub(crate) fn resolve_output_path(file: &Path, unit_name: &str, release: bool) -> Result<PathBuf> {
    if let Some(manifest_path) = gossamer_pkg::find_manifest(file) {
        let manifest_text =
            fs::read_to_string(&manifest_path).map_err(|e| friendly_io_error(e, &manifest_path))?;
        let manifest = gossamer_pkg::Manifest::parse(&manifest_text)
            .with_context(|| format!("parsing {}", manifest_path.display()))?;
        if let Some(output) = manifest.project.output {
            let raw = PathBuf::from(&output);
            let resolved = if raw.is_absolute() {
                raw
            } else {
                manifest_path
                    .parent()
                    .map_or_else(|| raw.clone(), |dir| dir.join(&raw))
            };
            return Ok(resolved);
        }
        if let Some(root) = manifest_path.parent() {
            let profile = if release { "release" } else { "debug" };
            let target_dir = root.join("target").join(profile);
            fs::create_dir_all(&target_dir)
                .map_err(|e| anyhow!("creating {}: {e}", target_dir.display()))?;
            return Ok(target_dir.join(unit_name));
        }
    }
    let parent = file.parent().filter(|p| !p.as_os_str().is_empty());
    let base = parent.map_or_else(|| PathBuf::from("."), Path::to_path_buf);
    let profile = if release { "release" } else { "debug" };
    let target_dir = base.join("target").join(profile);
    fs::create_dir_all(&target_dir)
        .map_err(|e| anyhow!("creating {}: {e}", target_dir.display()))?;
    Ok(target_dir.join(unit_name))
}

/// Returns the path the REPL uses to persist line-edit history
/// across sessions. Prefers `$GOSSAMER_HISTORY` → `$XDG_STATE_HOME/
/// gossamer/history` → `$HOME/.gossamer_history`. `None` is returned
/// only when no reasonable home directory can be discovered, in
/// which case history is kept in-memory for the current session.
pub(crate) fn repl_history_path() -> Option<PathBuf> {
    if let Ok(explicit) = std::env::var("GOSSAMER_HISTORY") {
        return Some(PathBuf::from(explicit));
    }
    if let Ok(state) = std::env::var("XDG_STATE_HOME") {
        let mut path = PathBuf::from(state);
        path.push("gossamer");
        let _ = fs::create_dir_all(&path);
        path.push("history");
        return Some(path);
    }
    if let Ok(home) = std::env::var("HOME") {
        let mut path = PathBuf::from(home);
        path.push(".gossamer_history");
        return Some(path);
    }
    None
}
