//! Seatbelt profile generation.
//!
//! A pure function from a compiled policy to a profile string, so the
//! part of the macOS backend most likely to be wrong is unit-tested on
//! any host, including the Linux and Windows CI jobs.
//!
//! Seatbelt matches on paths, not on inodes, so every path in the
//! profile is the resolved one: an unresolved symlink is a hole, and
//! the policy compiler has already canonicalized for exactly this
//! reason.

// Compiled on every host so the generator is unit-tested without a
// Mac; only the macOS backend calls it.
#![cfg_attr(not(target_os = "macos"), allow(dead_code))]

use crate::policy::{Access, CompiledPolicy, Network, Temp};

/// Mach services a process needs to start, plus the ones a compiler
/// toolchain genuinely asks for.
///
/// `com.apple.secinitd` is the one nothing runs without: every process
/// asks it whether it belongs in a container while `dyld` is still
/// initializing libraries, and `libsystem_secinit` aborts when the
/// answer does not come back. That abort happens before the program's
/// first instruction, so it prints nothing at all. The rest are name
/// resolution, logging, and notification delivery; anything not listed
/// is denied, which is the point.
const MACH_SERVICES: &[&str] = &[
    "com.apple.secinitd",
    "com.apple.system.opendirectoryd.libinfo",
    "com.apple.system.opendirectoryd.membership",
    "com.apple.system.notification_center",
    "com.apple.system.logger",
    "com.apple.logd",
    "com.apple.dyld",
    "com.apple.CoreServices.coreservicesd",
    "com.apple.diagnosticd",
    "com.apple.SecurityServer",
    "com.apple.SystemConfiguration.configd",
];

/// Directories every process needs merely to start.
const SYSTEM_READ_PATHS: &[&str] = &[
    "/usr/lib",
    "/usr/share",
    "/System/Library",
    "/Library/Preferences",
    "/private/var/db/dyld",
    // Since macOS 13 part of the system, the dyld shared cache included,
    // lives in a cryptex, and Seatbelt matches the path a file is
    // mounted at rather than the one it is presented under.
    "/System/Volumes/Preboot/Cryptexes",
    "/dev/null",
    "/dev/random",
    "/dev/urandom",
    "/dev/zero",
];

/// Operations a read grant covers.
///
/// Mapping a file as code has been its own operation since macOS 11, so
/// a profile that allows reads and not this one lets a process open a
/// dylib and not run it: the loader gives up before the program reaches
/// its first instruction, and it gives up by aborting rather than by
/// saying anything.
const READ_OPERATIONS: &str = "file-read* file-map-executable file-test-existence";

/// Operations a read-write grant covers, and the ones a denial names so
/// nothing it denies stays reachable through another operation.
const READ_WRITE_OPERATIONS: &str =
    "file-read* file-write* file-map-executable file-test-existence";

/// Renders `policy` as a Seatbelt profile.
#[must_use]
pub(crate) fn render(policy: &CompiledPolicy) -> String {
    let mut out = String::new();
    out.push_str("(version 1)\n");
    out.push_str(";; Generated by gossamer-sandbox. Deny by default; every\n");
    out.push_str(";; allowance below comes from one rule in the compiled policy.\n");
    out.push_str("(deny default)\n");
    out.push_str("(allow process-fork)\n");
    out.push_str("(allow process-info* (target same-sandbox))\n");
    out.push_str("(allow sysctl-read)\n");
    out.push_str("(allow signal (target same-sandbox))\n");

    // Exec is allowed unconditionally: a build is a tree of processes,
    // and the policy that matters is which binaries are reachable,
    // which the filesystem rules already answer. Denying exec here
    // would be the only rule in the model with no counterpart on Linux
    // or Windows.
    out.push_str("(allow process-exec*)\n");

    match policy.network {
        // Complete, every protocol - which is more than Landlock's
        // TCP-only layer can say.
        Network::None => out.push_str("(deny network*)\n"),
        // Seatbelt names the direction, so client-only is the outbound
        // filter over a closed default rather than a port rule.
        Network::Client => {
            out.push_str("(deny network*)\n");
            out.push_str("(allow network-outbound)\n");
        }
        Network::Open => out.push_str("(allow network*)\n"),
    }

    out.push_str("\n;; What every process needs before it reaches its own\n");
    out.push_str(";; first instruction. A denial here ends the program in the\n");
    out.push_str(";; loader, which aborts without printing anything.\n");
    // Resolving any path walks its ancestors, and Seatbelt asks for
    // metadata and an existence test on each one; a deny-default profile
    // that grants only subpaths cannot open a file whose parent it never
    // named. Contents stay denied - this is names, sizes, and times.
    out.push_str("(allow file-read-metadata file-test-existence)\n");
    // The working directory, which a shell resolves before anything else.
    out.push_str("(allow file-read* file-test-existence (literal \"/\"))\n");
    // `libsystem_secinit` asks the Sandbox policy whether this process
    // belongs in a container, and guarded vnodes are how the loader
    // opens what it maps.
    out.push_str("(allow system-mac-syscall (mac-policy-name \"vnguard\"))\n");
    out.push_str(
        "(allow system-mac-syscall (require-all (mac-policy-name \"Sandbox\") \
         (mac-syscall-number 67)))\n",
    );
    // libnotify registers against this shared segment as it initializes.
    out.push_str(
        "(allow ipc-posix-shm-read* (ipc-posix-name \"apple.shm.notification_center\"))\n",
    );

    out.push_str("\n;; System paths every process needs to start.\n");
    for path in SYSTEM_READ_PATHS {
        out.push_str(&format!(
            "(allow {READ_OPERATIONS} (subpath {}))\n",
            quote(path)
        ));
    }

    // libSystem registers with the DTrace helper as a process starts,
    // and the registration is an ioctl on this node rather than a read.
    out.push_str(
        "(allow file-read* file-test-existence file-write-data file-ioctl \
         (literal \"/dev/dtracehelper\"))\n",
    );

    out.push_str("\n;; Mach services a toolchain asks for; the rest are denied.\n");
    for service in MACH_SERVICES {
        out.push_str(&format!(
            "(allow mach-lookup (global-name {}))\n",
            quote(service)
        ));
    }

    out.push_str("\n;; The policy's own grants, most specific last so a later\n");
    out.push_str(";; rule overrides an earlier one, as Seatbelt evaluates them.\n");
    // Seatbelt takes the last matching rule, and the compiled policy is
    // ordered most-specific first, so the profile emits it reversed.
    for rule in policy.rules.iter().rev() {
        let path = rule.path.to_string_lossy();
        match rule.access {
            Access::ReadOnly => {
                out.push_str(&format!(
                    "(allow {READ_OPERATIONS} (subpath {}))\n",
                    quote(&path)
                ));
            }
            Access::ReadWrite => {
                out.push_str(&format!(
                    "(allow {READ_WRITE_OPERATIONS} (subpath {}))\n",
                    quote(&path)
                ));
            }
            Access::Deny => {
                out.push_str(&format!(
                    "(deny {READ_WRITE_OPERATIONS} (subpath {}))\n",
                    quote(&path)
                ));
            }
        }
    }

    if let Temp::Path(path) = &policy.temp {
        out.push_str(&format!(
            "(allow {READ_WRITE_OPERATIONS} (subpath {}))\n",
            quote(&path.to_string_lossy())
        ));
    }
    out
}

/// Quotes a path as a Seatbelt string literal.
///
/// A path containing a quote or a backslash would otherwise end the
/// literal early and turn the rest of the path into profile syntax,
/// which is a policy bypass rather than a formatting bug.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        if ch == '"' || ch == '\\' {
            out.push('\\');
        }
        out.push(ch);
    }
    out.push('"');
    out
}

#[cfg(test)]
mod profile_tests {
    use super::*;
    use crate::policy::SandboxPolicy;

    fn compiled() -> CompiledPolicy {
        let root = std::env::temp_dir();
        SandboxPolicy::new()
            .read_write(&root)
            .compile()
            .expect("compile")
    }

    #[test]
    fn the_profile_denies_by_default() {
        let rendered = render(&compiled());
        assert!(rendered.starts_with("(version 1)"));
        assert!(rendered.contains("(deny default)"), "{rendered}");
    }

    #[test]
    fn the_loader_reaches_what_it_needs_before_any_grant_of_the_policy() {
        let rendered = render(&compiled());
        // A process that cannot map the shared cache, stat a path's
        // ancestors, or register with the DTrace helper never reaches
        // its own first instruction.
        assert!(
            rendered.contains("(subpath \"/System/Volumes/Preboot/Cryptexes\")"),
            "{rendered}"
        );
        assert!(
            rendered.contains("(allow file-read-metadata file-test-existence)"),
            "{rendered}"
        );
        // Nothing starts without asking whether it belongs in a
        // container, and nothing answers that but this service.
        assert!(rendered.contains("com.apple.secinitd"), "{rendered}");
        assert!(rendered.contains("/dev/dtracehelper"), "{rendered}");
        // Reading a dylib is not permission to run it.
        assert!(rendered.contains("file-map-executable"), "{rendered}");
    }

    #[test]
    fn network_denial_covers_every_protocol() {
        let rendered = render(&compiled());
        assert!(rendered.contains("(deny network*)"), "{rendered}");
    }

    #[test]
    fn a_grant_becomes_a_subpath_rule_on_the_resolved_path() {
        let root = std::env::temp_dir().canonicalize().expect("canonicalize");
        let rendered = render(&compiled());
        assert!(
            rendered.contains(&format!(
                "(allow {READ_WRITE_OPERATIONS} (subpath {}))",
                quote(&root.to_string_lossy())
            )),
            "{rendered}"
        );
    }

    #[test]
    fn a_denial_is_emitted_after_the_grant_it_overrides() {
        let root = std::env::temp_dir().canonicalize().expect("canonicalize");
        let inner = root.join("gos-sandbox-profile-inner");
        std::fs::create_dir_all(&inner).expect("create fixture");
        let policy = SandboxPolicy::new()
            .read_write(&root)
            .deny(&inner)
            .compile()
            .expect("compile");
        let rendered = render(&policy);
        let grant = rendered
            .find(&format!("(subpath {}))", quote(&root.to_string_lossy())))
            .expect("grant present");
        let denial = rendered
            .find(&format!("(subpath {}))", quote(&inner.to_string_lossy())))
            .expect("denial present");
        assert!(
            denial > grant,
            "Seatbelt takes the last matching rule, so the more specific one must come last"
        );
    }

    #[test]
    fn a_path_with_a_quote_cannot_end_the_literal_early() {
        assert_eq!(quote("/tmp/a\"b"), "\"/tmp/a\\\"b\"");
        assert_eq!(quote("/tmp/a\\b"), "\"/tmp/a\\\\b\"");
    }

    #[test]
    fn every_mach_service_is_named_explicitly() {
        let rendered = render(&compiled());
        for service in MACH_SERVICES {
            assert!(rendered.contains(service), "{service} missing");
        }
        assert!(
            !rendered.contains("(allow mach-lookup)"),
            "an unqualified mach-lookup allowance would grant every service"
        );
    }
}
