//! Workspace automation entry point.
//! Invoked via `cargo xtask <command>`. Current subcommands:
//! - `docs-stdlib` — regenerate `docs_src/stdlib.md` from the
//!   `gossamer_std` manifest so the rendered reference page tracks
//!   the single source of truth.
//! - `docs-lints` — regenerate `docs_src/toolchain/lints.md` from the
//!   `gossamer-lint` crate's `DAY_ONE_LINTS` + `lint_explanation`.
//! - `docs-diagnostics` — regenerate `docs_src/toolchain/diagnostics.md`
//!   from the curated catalogue in this file.
//! - `stdlib-coverage` — regenerate `docs_src/stdlib_coverage.md`
//!   from the per-module support state recorded in
//!   [`STDLIB_SUPPORT`].
//! - `docs-all` — run every generator above in one invocation.

#![forbid(unsafe_code)]

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use gossamer_std::{StdItemKind, StdModule, modules};

/// Entry point that dispatches to the requested xtask subcommand.
fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        None => {
            println!("usage: cargo xtask <subcommand>");
            println!("subcommands:");
            println!("  docs-stdlib         regenerate docs_src/stdlib.md");
            println!("  docs-lints          regenerate docs_src/toolchain/lints.md");
            println!("  docs-diagnostics    regenerate docs_src/toolchain/diagnostics.md");
            println!("  stdlib-coverage     regenerate docs_src/stdlib_coverage.md");
            println!("  docs-all            run every docs generator");
            Ok(())
        }
        Some("docs-stdlib") => regenerate_stdlib_docs(),
        Some("docs-lints") => regenerate_lint_docs(),
        Some("docs-diagnostics") => regenerate_diagnostic_docs(),
        Some("stdlib-coverage") => regenerate_stdlib_coverage(),
        Some("docs-all") => {
            regenerate_stdlib_docs()?;
            regenerate_lint_docs()?;
            regenerate_diagnostic_docs()?;
            regenerate_stdlib_coverage()
        }
        Some(other) => {
            eprintln!("xtask: unknown subcommand {other:?}");
            std::process::exit(2);
        }
    }
}

/// Rewrites `docs_src/stdlib.md` using the data in
/// [`gossamer_std::modules`]. The generated page starts with a
/// marker line so the regeneration is idempotent and consumers can
/// diff against the previous version.
fn regenerate_stdlib_docs() -> Result<()> {
    let workspace_root = locate_workspace_root()?;
    let out_path = workspace_root.join("docs_src/stdlib.md");
    let page = render_stdlib_page(modules());
    fs::write(&out_path, page).with_context(|| format!("writing {}", out_path.display()))?;
    println!("xtask: wrote {}", out_path.display());
    Ok(())
}

/// Walks parent directories from `CARGO_MANIFEST_DIR` until it finds
/// one containing a workspace-root `Cargo.toml`.
fn locate_workspace_root() -> Result<PathBuf> {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").map_or_else(|_| PathBuf::from("."), PathBuf::from);
    let mut cursor: &Path = &manifest_dir;
    loop {
        if cursor.join("Cargo.lock").exists() {
            return Ok(cursor.to_path_buf());
        }
        match cursor.parent() {
            Some(parent) => cursor = parent,
            None => {
                anyhow::bail!(
                    "could not locate workspace root from {}",
                    manifest_dir.display()
                );
            }
        }
    }
}

/// Renders the stdlib reference page as Markdown.
fn render_stdlib_page(modules: &[StdModule]) -> String {
    let mut out = String::new();
    writeln!(out, "<!-- generated by `cargo xtask docs-stdlib` -->").unwrap();
    writeln!(out, "# Standard library").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Gossamer's standard library ships as a Rust-implemented host\n\
         crate (`gossamer-std`) with a manifest describing every\n\
         module and item. This page is auto-generated from that\n\
         manifest via `cargo xtask docs-stdlib`; hand edits are\n\
         overwritten on the next regeneration."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "The manifest itself lives at [`crates/gossamer-std/src/manifest.rs`](\
         https://github.com/gossamer-lang/gossamer/blob/main/crates/gossamer-std/src/manifest.rs)."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## Modules").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "| Module | Items | Summary |").unwrap();
    writeln!(out, "|--------|------:|---------|").unwrap();
    let mut sorted: Vec<&StdModule> = modules.iter().collect();
    sorted.sort_by_key(|m| m.path);
    for module in &sorted {
        writeln!(
            out,
            "| [`{path}`](#{anchor}) | {count} | {summary} |",
            path = module.path,
            anchor = module_anchor(module.path),
            count = module.items.len(),
            summary = module.summary,
        )
        .unwrap();
    }
    writeln!(out).unwrap();
    for module in &sorted {
        write_module_section(&mut out, module);
    }
    out
}

/// Emits one module's detail block — heading, summary, item table.
fn write_module_section(out: &mut String, module: &StdModule) {
    writeln!(out, "## `{}`", module.path).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{}", module.summary).unwrap();
    writeln!(out).unwrap();
    if module.items.is_empty() {
        writeln!(out, "*No items exported yet.*").unwrap();
        writeln!(out).unwrap();
        return;
    }
    writeln!(out, "| Item | Kind | Doc |").unwrap();
    writeln!(out, "|------|------|-----|").unwrap();
    let mut items: Vec<&gossamer_std::StdItem> = module.items.iter().collect();
    items.sort_by_key(|i| (kind_rank(i.kind), i.name));
    for item in items {
        writeln!(
            out,
            "| `{name}` | {kind} | {doc} |",
            name = item.name,
            kind = kind_label(item.kind),
            doc = item.doc,
        )
        .unwrap();
    }
    writeln!(out).unwrap();
}

/// GitHub-style slug for a module path suitable for markdown anchors.
fn module_anchor(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    for ch in path.chars() {
        match ch {
            'A'..='Z' => out.push(ch.to_ascii_lowercase()),
            'a'..='z' | '0'..='9' | '-' => out.push(ch),
            _ => {}
        }
    }
    out
}

/// Human-friendly column label for a manifest `StdItemKind`.
fn kind_label(kind: StdItemKind) -> &'static str {
    match kind {
        StdItemKind::Function => "fn",
        StdItemKind::Type => "type",
        StdItemKind::Trait => "trait",
        StdItemKind::Macro => "macro",
        StdItemKind::Const => "const",
    }
}

/// Sort weight so item tables list types first, then traits, then
/// functions, then macros, then constants — matches the progression
/// a reader scanning for "what's here" expects.
fn kind_rank(kind: StdItemKind) -> u8 {
    match kind {
        StdItemKind::Type => 0,
        StdItemKind::Trait => 1,
        StdItemKind::Function => 2,
        StdItemKind::Macro => 3,
        StdItemKind::Const => 4,
    }
}

/// Rewrites `docs_src/toolchain/lints.md` from the lint crate's
/// day-one ID list and `lint_explanation` entries.
fn regenerate_lint_docs() -> Result<()> {
    let workspace_root = locate_workspace_root()?;
    let out_dir = workspace_root.join("docs_src/toolchain");
    fs::create_dir_all(&out_dir).with_context(|| format!("mkdir {}", out_dir.display()))?;
    let out_path = out_dir.join("lints.md");
    let page = render_lints_page(gossamer_lint::DAY_ONE_LINTS);
    fs::write(&out_path, page).with_context(|| format!("writing {}", out_path.display()))?;
    println!("xtask: wrote {}", out_path.display());
    Ok(())
}

fn render_lints_page(ids: &[&str]) -> String {
    let mut out = String::new();
    writeln!(out, "<!-- generated by `cargo xtask docs-lints` -->").unwrap();
    writeln!(out, "# Lints").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "The Gossamer linter ships {n} day-one checks. Each has a short\n\
         identifier suitable for `#[lint(allow(...))]` and a long-form\n\
         explanation available via `gos lint --explain <id>`. This page\n\
         is auto-generated from `gossamer-lint`; hand edits are\n\
         overwritten on the next run of `cargo xtask docs-lints`.",
        n = ids.len()
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "| Code | Identifier | Default |").unwrap();
    writeln!(out, "|------|------------|---------|").unwrap();
    for (i, id) in ids.iter().enumerate() {
        let code = format!("GL{:04}", i + 1);
        let default = default_level_for(id);
        writeln!(out, "| `{code}` | [`{id}`](#{id}) | {default} |").unwrap();
    }
    writeln!(out).unwrap();
    for id in ids {
        writeln!(out, "## `{id}`").unwrap();
        writeln!(out).unwrap();
        match gossamer_lint::lint_explanation(id) {
            Some(explanation) => {
                for line in explanation.lines() {
                    writeln!(out, "{}", line.trim_start()).unwrap();
                }
            }
            None => {
                writeln!(out, "*No explanation registered.*").unwrap();
            }
        }
        writeln!(out).unwrap();
    }
    out
}

fn default_level_for(id: &str) -> &'static str {
    let registry = gossamer_lint::Registry::with_defaults();
    match registry.level(id) {
        gossamer_lint::Level::Deny => "deny",
        gossamer_lint::Level::Warn => "warn",
        gossamer_lint::Level::Allow => "allow",
    }
}

/// Rewrites `docs_src/toolchain/diagnostics.md` from the catalogue
/// of diagnostic codes emitted by the compiler phases.
fn regenerate_diagnostic_docs() -> Result<()> {
    let workspace_root = locate_workspace_root()?;
    let out_dir = workspace_root.join("docs_src/toolchain");
    fs::create_dir_all(&out_dir).with_context(|| format!("mkdir {}", out_dir.display()))?;
    let out_path = out_dir.join("diagnostics.md");
    let page = render_diagnostics_page(DIAGNOSTIC_CATALOGUE);
    fs::write(&out_path, page).with_context(|| format!("writing {}", out_path.display()))?;
    println!("xtask: wrote {}", out_path.display());
    Ok(())
}

/// Catalogue of diagnostic codes emitted by the compiler. Each entry
/// is `(code, phase, title, explanation)`. Keep in sync with the
/// emitters in `gossamer-parse`, `gossamer-resolve`, `gossamer-types`,
/// and `gossamer-pkg`.
const DIAGNOSTIC_CATALOGUE: &[(&str, &str, &str, &str)] = &[
    (
        "GP0001",
        "Parser",
        "unexpected token",
        "The parser saw a token where it expected a different one. Check for missing punctuation, an unmatched delimiter, or an out-of-place keyword.",
    ),
    (
        "GP0002",
        "Parser",
        "unexpected end of input",
        "The parser reached end-of-file in the middle of a construct. Finish the expression, statement, or item — or remove it.",
    ),
    (
        "GP0003",
        "Parser",
        "unterminated delimiter",
        "A balanced construct (block, tuple, array, string literal) was left unterminated. Add the matching closing delimiter.",
    ),
    (
        "GP0004",
        "Parser",
        "chained comparison without parentheses",
        "Comparison operators like `==` / `!=` / `<` are not associative. Parenthesise the operands: `(a == b) && (b == c)`.",
    ),
    (
        "GR0001",
        "Resolve",
        "unresolved name",
        "A name used in source could not be resolved to a declaration. Check the spelling, whether a `use` brings the name into scope, and whether the item is visible at this location.",
    ),
    (
        "GR0002",
        "Resolve",
        "wrong namespace",
        "A name was resolved to the wrong namespace (value vs. type). Check the declaration and the spelling.",
    ),
    (
        "GR0003",
        "Resolve",
        "duplicate item",
        "Two items in the same module share a name. Rename one of them or move it into a distinct `mod`.",
    ),
    (
        "GR0004",
        "Resolve",
        "duplicate import",
        "The same path was imported twice in the same `use` list. Drop the duplicate.",
    ),
    (
        "GT0001",
        "Types",
        "type mismatch",
        "The type checker could not reconcile two types it expected to match. The primary label shows the location of the mismatch; the `note:` line names the conflicting types.",
    ),
    (
        "GT0002",
        "Types",
        "unresolved method",
        "The type checker could not find a method with the supplied name on the receiver type. Check for a typo, a missing `use`, or a trait impl that lives in an unreachable module.",
    ),
    (
        "GT0003",
        "Types",
        "unresolved operator",
        "The operator is not defined for the operand types. Check the operand types and use the correct operator.",
    ),
    (
        "GT0004",
        "Match exhaustiveness",
        "non-exhaustive match",
        "A `match` expression does not cover every possible value. Add an arm for the pattern(s) listed under `help:`.",
    ),
    (
        "GT0005",
        "Types",
        "non-primitive cast",
        "The `as` cast is restricted to a whitelist: numeric ↔ numeric, `bool`/`char` → integer, `u8` → `char`, and same-type no-ops. Struct / enum / String sources are rejected. Use a conversion method when you need serialisation; `as` does not run code.",
    ),
    (
        "GK0001",
        "Package manager",
        "manifest parse error",
        "The package manifest (`gos.toml`) could not be parsed. Check the TOML syntax and required fields.",
    ),
];

fn render_diagnostics_page(entries: &[(&str, &str, &str, &str)]) -> String {
    let mut out = String::new();
    writeln!(out, "<!-- generated by `cargo xtask docs-diagnostics` -->").unwrap();
    writeln!(out, "# Diagnostic codes").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Every compiler diagnostic carries a four-character prefix plus\n\
         a four-digit number: `GP` for the parser / lexer, `GR` for\n\
         name resolution, `GT` for the type checker, `GM` for match\n\
         exhaustiveness, `GL` for lint framework, `GK` for the package\n\
         manager. Use `gos explain <code>` for the interactive\n\
         version. This page is auto-generated from the catalogue in\n\
         `xtask/src/main.rs`; hand edits are overwritten by\n\
         `cargo xtask docs-diagnostics`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "| Code | Phase | Title |").unwrap();
    writeln!(out, "|------|-------|-------|").unwrap();
    for (code, phase, title, _) in entries {
        let anchor = code.to_ascii_lowercase();
        writeln!(out, "| [`{code}`](#{anchor}) | {phase} | {title} |").unwrap();
    }
    writeln!(out).unwrap();
    for (code, phase, title, explanation) in entries {
        let anchor = code.to_ascii_lowercase();
        writeln!(out, "## `{code}` <a id=\"{anchor}\"></a>").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "**{phase}** — {title}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{explanation}").unwrap();
        writeln!(out).unwrap();
    }
    out
}

/// Coverage state for a stdlib module across the toolchain's
/// execution paths. Hand-curated in [`STDLIB_SUPPORT`]; updated
/// in PRs that wire a previously-missing item.
#[derive(Clone, Copy)]
struct StdlibSupport {
    path: &'static str,
    interp: Coverage,
    compiled: Coverage,
    tested: Coverage,
    notes: &'static str,
}

#[derive(Clone, Copy)]
#[allow(
    dead_code,
    reason = "Missing is used by the table only when a module regresses"
)]
enum Coverage {
    Full,
    Partial,
    Missing,
}

impl Coverage {
    fn glyph(self) -> &'static str {
        match self {
            Self::Full => "✓",
            Self::Partial => "◑",
            Self::Missing => "✗",
        }
    }
}

const STDLIB_SUPPORT: &[StdlibSupport] = &[
    item(
        "std::fmt",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "println / print / eprintln / eprint / format / write / writeln.",
    ),
    item(
        "std::io",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "stdout, stderr, stdin, write, write_byte, write_byte_array, flush, read_line, read_to_string.",
    ),
    item(
        "std::os",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "args, env, exit, read_file, write_file, mkdir, mkdir_all, read_dir.",
    ),
    item(
        "std::os::exec",
        Coverage::Partial,
        Coverage::Partial,
        Coverage::Full,
        "Command builder + output / status / spawn / kill / wait. Stdlib + tests; interp/MIR wiring pending.",
    ),
    item(
        "std::os::signal",
        Coverage::Partial,
        Coverage::Partial,
        Coverage::Full,
        "on(SIGTERM/SIGINT/SIGHUP/SIGUSR1/SIGUSR2/SIGQUIT). Stdlib + tests; runtime signal-handler bridge pending.",
    ),
    item(
        "std::strings",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "split, trim, contains, find, replace, to_lowercase, to_uppercase, starts_with, ends_with.",
    ),
    item(
        "std::strconv",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "parse_i64, parse_u64, parse_f64, parse_bool, format_i64, format_f64.",
    ),
    item(
        "std::collections",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Vec, HashMap. VecDeque/BTreeMap/HashSet/BTreeSet declared.",
    ),
    item(
        "std::net",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "TcpListener, TcpStream. UdpSocket partial.",
    ),
    item(
        "std::http",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "HTTP/1.1 server + client. HTTP/2 deferred to v1.x.",
    ),
    item(
        "std::encoding::json",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "encode + decode + Value.",
    ),
    item(
        "std::encoding::base64",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "encode + decode.",
    ),
    item(
        "std::encoding::hex",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "encode + decode.",
    ),
    item(
        "std::encoding::binary",
        Coverage::Partial,
        Coverage::Partial,
        Coverage::Partial,
        "put_u16_be, put_u32_be only — get_*, le variants pending.",
    ),
    item(
        "std::sync",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Mutex, WaitGroup, AtomicI64. RwLock, Once partial.",
    ),
    item(
        "std::time",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "now, sleep, format_rfc3339, parse_rfc3339.",
    ),
    item(
        "std::panic",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "panic + catch_unwind.",
    ),
    item(
        "std::errors",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "new, wrap, is, chain, join.",
    ),
    item(
        "std::flag",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Set with string/int/uint/float/bool/duration/string_list, --help, equals form. Subcommands deferred to v1.x.",
    ),
    item(
        "std::path",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "join, split, base, dir, ext, clean.",
    ),
    item(
        "std::path::native",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "SEPARATOR, join, clean, to_posix, to_native.",
    ),
    item(
        "std::fs",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "read_dir, walk_dir, mkdir_all, remove_all, copy, rename.",
    ),
    item(
        "std::bytes",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Buffer, Builder, index_of, split, replace.",
    ),
    item(
        "std::bufio",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Reader, Writer, Scanner with split_lines / split_words.",
    ),
    item(
        "std::net::url",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Url, query_escape, query_unescape.",
    ),
    item(
        "std::slog",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Logger, Field, TextHandler, JsonHandler with escape coverage.",
    ),
    item(
        "std::context",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "background, with_cancel, with_deadline, with_timeout.",
    ),
    item(
        "std::crypto::rand",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "fill, bytes.",
    ),
    item(
        "std::crypto::sha256",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "digest, hex.",
    ),
    item(
        "std::crypto::hmac",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "sha256_mac.",
    ),
    item(
        "std::crypto::subtle",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "constant_time_eq.",
    ),
    item(
        "std::sort",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "sort, sort_stable, binary_search.",
    ),
    item(
        "std::utf8",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "is_valid, rune_count.",
    ),
    item(
        "std::math::rand",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Rng (SplitMix64).",
    ),
    item(
        "std::testing",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "Runner, check, check_eq, check_ok.",
    ),
    item(
        "std::runtime",
        Coverage::Partial,
        Coverage::Partial,
        Coverage::Partial,
        "max_procs, set_max_procs, num_cpus. mem_stats partial.",
    ),
    item(
        "std::tls",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "rustls-backed; ServerConfig, ClientConfig.",
    ),
    item(
        "std::regex",
        Coverage::Full,
        Coverage::Full,
        Coverage::Full,
        "compile, is_match, find, find_all, captures, replace, split.",
    ),
    item(
        "std::compress::gzip",
        Coverage::Partial,
        Coverage::Partial,
        Coverage::Full,
        "encode/decode + Level. Stdlib + tests via flate2; interp/MIR wiring pending.",
    ),
];

const fn item(
    path: &'static str,
    interp: Coverage,
    compiled: Coverage,
    tested: Coverage,
    notes: &'static str,
) -> StdlibSupport {
    StdlibSupport {
        path,
        interp,
        compiled,
        tested,
        notes,
    }
}

/// Rewrites `docs_src/stdlib_coverage.md` from the curated table.
fn regenerate_stdlib_coverage() -> Result<()> {
    let workspace_root = locate_workspace_root()?;
    let out_path = workspace_root.join("docs_src/stdlib_coverage.md");
    let page = render_stdlib_coverage_page(STDLIB_SUPPORT);
    fs::write(&out_path, page).with_context(|| format!("writing {}", out_path.display()))?;
    println!("xtask: wrote {}", out_path.display());
    Ok(())
}

fn render_stdlib_coverage_page(items: &[StdlibSupport]) -> String {
    let mut out = String::new();
    writeln!(out, "<!-- generated by `cargo xtask stdlib-coverage` -->").unwrap();
    writeln!(out, "# Stdlib coverage matrix").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Auto-generated. Do not hand-edit. Re-run `cargo xtask\n\
         stdlib-coverage` after changing the support state of a\n\
         module."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Columns:\n\n\
         - **Interp** — `gos run` (bytecode VM + tree-walker fallback).\n\
         - **Compiled** — `gos build` (Cranelift) and `gos build --release` (LLVM).\n\
         - **Tests** — at least one integration test exercising the item.\n\n\
         Glyphs: ✓ supported · ◑ partial · ✗ missing.\n"
    )
    .unwrap();
    writeln!(out, "| Module | Interp | Compiled | Tests | Notes |").unwrap();
    writeln!(out, "|--------|:------:|:--------:|:-----:|-------|").unwrap();
    for entry in items {
        writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            entry.path,
            entry.interp.glyph(),
            entry.compiled.glyph(),
            entry.tested.glyph(),
            entry.notes,
        )
        .unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, "## How to regenerate this page").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "```sh\ncargo xtask stdlib-coverage\n```").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## How to interpret the columns").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "- A module is marked `Interp ✓` when at least one of its\n\
         items resolves through `gossamer-interp::builtins::install`.\n\
         A `◑` means some items resolve and some do not.\n\
         A `✗` means none of the items are wired.\n\n\
         - A module is marked `Compiled ✓` when at least one of its\n\
         items has a runtime symbol declared in\n\
         `gossamer-codegen-llvm/src/emit.rs::RUNTIME_DECLARATIONS`\n\
         and a Cranelift import in\n\
         `gossamer-codegen-cranelift/src/native.rs`, or is\n\
         dispatched as a method via\n\
         `gossamer-mir/src/lower.rs::lower_method_call`.\n\n\
         - A module is marked `Tests ✓` when at least one\n\
         integration / parity / phase test exercises it."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## Cross-references").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "- [`stdlib.md`](stdlib.md) — module index with summaries.\n\
         - [`method_support.md`](method_support.md) — per-method\n\
           reference for shipped types.\n\
         - [`non_goals_v1.md`](non_goals_v1.md) — what's deferred to\n\
           v1.x."
    )
    .unwrap();
    out
}
