//! Credential store for `gos publish` / `gos yank`.
//!
//! Tokens live in `~/.gossamer/credentials.toml`, mode 600. The
//! schema is a simple `[registries."<URL>"]` table per server with
//! a single `token = "…"` field.
//!
//! `gos login --registry URL` writes a token (interactively or from
//! `$GOS_TOKEN`); `gos logout --registry URL` removes it. Every
//! authenticated registry request sends `Authorization: Bearer <token>`.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use thiserror::Error;

/// Errors raised by the credential store.
#[derive(Debug, Error)]
pub enum CredentialStoreError {
    /// I/O error reading or writing the credential file.
    #[error("io: {0}")]
    Io(String),
    /// File is present but contained no parseable entries.
    #[error("malformed credentials: {0}")]
    Malformed(String),
    /// `HOME` was unset and no explicit path was provided.
    #[error("HOME not set; cannot locate credential store")]
    NoHome,
}

/// Single credential entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Credential {
    /// Bearer token sent in the `Authorization` header.
    pub token: String,
}

/// File-backed credential store keyed by registry URL.
#[derive(Debug, Clone, Default)]
pub struct CredentialStore {
    /// Per-registry credential entries.
    pub entries: BTreeMap<String, Credential>,
}

impl CredentialStore {
    /// Returns an empty in-memory store.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns the canonical credential-file path: either
    /// `$GOS_CREDENTIALS_FILE`, `$HOME/.gossamer/credentials.toml`,
    /// or `Err(NoHome)` when neither is set.
    pub fn default_path() -> Result<PathBuf, CredentialStoreError> {
        if let Ok(env_path) = std::env::var("GOS_CREDENTIALS_FILE") {
            return Ok(PathBuf::from(env_path));
        }
        let home = std::env::var("HOME").map_err(|_| CredentialStoreError::NoHome)?;
        Ok(PathBuf::from(home)
            .join(".gossamer")
            .join("credentials.toml"))
    }

    /// Loads the store from `path`. Returns an empty store when the
    /// file does not exist.
    pub fn load(path: &Path) -> Result<Self, CredentialStoreError> {
        match fs::read_to_string(path) {
            Ok(text) => Self::parse(&text).map_err(CredentialStoreError::Malformed),
            Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(Self::new()),
            Err(err) => Err(CredentialStoreError::Io(err.to_string())),
        }
    }

    /// Loads the store from the canonical path.
    pub fn load_default() -> Result<Self, CredentialStoreError> {
        let path = Self::default_path()?;
        Self::load(&path)
    }

    /// Returns the credential for `registry_url`, if any.
    #[must_use]
    pub fn get(&self, registry_url: &str) -> Option<&Credential> {
        self.entries.get(registry_url)
    }

    /// Stores `credential` under `registry_url`.
    pub fn insert(&mut self, registry_url: impl Into<String>, credential: Credential) {
        self.entries.insert(registry_url.into(), credential);
    }

    /// Removes the entry for `registry_url`, returning whether one
    /// was present.
    pub fn remove(&mut self, registry_url: &str) -> bool {
        self.entries.remove(registry_url).is_some()
    }

    /// Writes the store to `path` atomically (write-to-tmp + rename)
    /// with mode 600 on POSIX.
    pub fn save(&self, path: &Path) -> Result<(), CredentialStoreError> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|e| CredentialStoreError::Io(e.to_string()))?;
        }
        let tmp = path.with_extension("toml.new");
        let text = self.render();
        fs::write(&tmp, text.as_bytes()).map_err(|e| CredentialStoreError::Io(e.to_string()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&tmp)
                .map_err(|e| CredentialStoreError::Io(e.to_string()))?
                .permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&tmp, perms)
                .map_err(|e| CredentialStoreError::Io(e.to_string()))?;
        }
        fs::rename(&tmp, path).map_err(|e| CredentialStoreError::Io(e.to_string()))?;
        Ok(())
    }

    /// Writes the store to the canonical path.
    pub fn save_default(&self) -> Result<(), CredentialStoreError> {
        let path = Self::default_path()?;
        self.save(&path)
    }

    /// Renders the store to canonical TOML.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# gossamer credentials store v1\n");
        out.push_str("# Generated by `gos login`. Do not commit.\n\n");
        for (url, cred) in &self.entries {
            out.push_str(&format!("[registries.{}]\n", quote(url)));
            out.push_str(&format!("token = {}\n\n", quote(&cred.token)));
        }
        out
    }

    /// Parses a credential file previously produced by [`Self::render`].
    pub fn parse(text: &str) -> Result<Self, String> {
        let mut entries: BTreeMap<String, Credential> = BTreeMap::new();
        let mut current_url: Option<String> = None;
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(inner) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                if let Some(after) = inner.trim().strip_prefix("registries.") {
                    let url = unquote(after.trim());
                    current_url = Some(url);
                } else {
                    return Err(format!("unknown section [{inner}]"));
                }
                continue;
            }
            let (key, value) = line
                .split_once('=')
                .ok_or_else(|| format!("malformed credential line: {line}"))?;
            let key = key.trim();
            let value = unquote(value.trim());
            let url = current_url
                .clone()
                .ok_or_else(|| format!("entry {key} outside of [registries.…]"))?;
            if key == "token" {
                entries.insert(url, Credential { token: value });
            }
        }
        Ok(Self { entries })
    }
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        if c == '\\' || c == '"' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

fn unquote(s: &str) -> String {
    let trimmed = s.trim();
    let Some(inner) = trimmed.strip_prefix('"').and_then(|x| x.strip_suffix('"')) else {
        return trimmed.to_string();
    };
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c == '\\'
            && let Some(next) = chars.next()
        {
            out.push(next);
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn store_round_trips_through_text() {
        let mut store = CredentialStore::new();
        store.insert(
            "https://pkg.gossamer.dev",
            Credential {
                token: "abc.def.ghi".to_string(),
            },
        );
        let rendered = store.render();
        let back = CredentialStore::parse(&rendered).unwrap();
        assert_eq!(
            back.get("https://pkg.gossamer.dev").unwrap().token,
            "abc.def.ghi"
        );
    }
}
